### ISSUE TITLE
Matlab exit time not considered

### ISSUE THREAD

**Issue by jvlmdr** [votchallenge/vot-toolkit#100]
Matlab takes a significant amount of time to exit as well as to start. On my desktop, the amount of time to start Matlab is 3.50 sec and the amount of time to start and exit Matlab is 5.43 sec (mean of 8 trials). This has a significant impact on the running time of a tracker I'm testing:

| startup time | actual speed | normalized speed |
| --- | --- | --- |
| 3.50 | 32.7 | 19.1 |
| 5.43 | 47.5 | 27.8 |

I think it can be fixed by replacing some of the code in tracker/benchmark_hardware.m with

```
    matlab_executable = [fullfile(strrep(matlabroot, ' ', '\ '), 'bin', 'matlab'), ' -nodesktop -nosplash -r "exit;"'];
    % ...
        repetitions = 8;
        totaltime = 0;
        for i = 1:repetitions
            tic;
            if verLessThan('matlab', '7.14.0')
                [result, output] = system(matlab_executable);
            else
                [result, output] = system(matlab_executable, '');
            end;
            totaltime = totaltime + toc;
        end;
    % ...
```

**Comment by lukacu** [comment]
Hi, thank you for your report. I totally agree and I have thought that we have already taken this into account, but it may be that it was negated by latter other changes. Anyway, I will check your proposed fix next week and if it works I will merge it as soon as possible.

**Comment by lukacu** [comment]
With the changes introduced in the 5.0 release this is no longer relevant, so I am closing the issue.
