### ISSUE TITLE
syntax error?

### ISSUE THREAD

**Issue by chkap** [votchallenge/vot-toolkit#105]
At vot-toolkit/analysis/create_sequence_selectors.m, line 76:
`trajectory{end+1:length(groundtruth)} = 0;`
This seems to be illegal. trajectory is a cell array, the content accessment via curly braces will return a list expression. It is illegal to assign 0 to it.

I have tested it on Matlab 2015b, and Matlab 2016b. And errors happen when some tracker trajectory results are shorter than the groundtruths, in which case the above line will be executed.

Maybe, the above line should be replaced with:
`for idx_tmp = length(groundtruth):-1:length(trajectory)+1`
      `trajectory{idx_tmp,1}=0;`
`end`

**Comment by lukacu** [comment]
This is strange, which benchmark were you running? In any case, I will check it out and apply the proposed fix if it is needed. Thanks.

**Comment by chkap** [comment]
I'm running the vot2016 benchmark.

**Comment by Jim61C** [comment]
Same issue encountered when running VOT2016 benchmark, is it fixed somewhere? Thanks!

**Comment by lukacu** [comment]
I did not have time to work on the toolkit as I am currently busy with other projects. I have to investigate the cause of the error. No tracker should have trajectory shorter than the groundtruth ... but I have not checked if the error occurs in the benchmark results. Can you tell me which tracker is problematic so that we may have a look?

**Comment by Jim61C** [comment]
Hi!

I first encountered this problem with ACT. And later realize that it also
happens against the 2nd tracker in the trackers.txt of the VOT2016_results.
I tried the solution of making the syntax correct but then I run into
problems of Matlab crashing. I am using Matlab 2017a. I was able to
generate reports for 2014 and 2015 benchmarks but I just had this issue
with the 2016 benchmark.

Thank you!

**Comment by Jim61C** [comment]
Just another piece of information that the problem first appeared with the sequence car2 and I have in fact checked the results of ACT, for each run, I am observing the same lines of results as compared to the groundtruth. However, one thing I realise is that ACT only had 3 repetitions when the vot2016 specifies number of repetitions for baseline to be 15. Hope these information helps! Thanks!

**Comment by lukacu** [comment]
Thanks for the info. @alanlukezic: can you have a look at the results for VOT2016 if there are indeed any problems like described here?

**Comment by alanlukezic** [comment]
Three repetitions are not the problem, because toolkit runs a tracker only three times if it is deterministic. How did you run analysis and what experiments did you use? 
If I use the command (in run_analysis.m script), it works ok:
report_article(context, experiments(1), trackers, sequences);

**Comment by Jim61C** [comment]
I am running the following command,

context = create_report_context('report_vot2016_MDNET_CPLUSPLUS_MY_SCHEME');  
report_article(context, experiments, trackers, sequences);

May I know what does experiments(1) mean, does it mean that it runs on one run file? Thanks!

In addition, may I know which branch and commit you are on for the toolkit that your run_analysis works?
Thank you!

**Comment by Jim61C** [comment]
By the way, I am using 

trackers = order_trackers(tracker_list('MDNET_CPLUSPLUS_MY_SCHEME', 'results/trackers.txt')); 

to generate the list of trackers for vot2016 for your kind reference.

**Comment by alanlukezic** [comment]
VOT16 has two types of experiments: baseline (reset-based) and unsupervised (no-reset experiment), so experiments(1) means that evaluation is performed on the baseline experiment only. Did you try to perform analysis only on the first experiment?
I think that this kind of trackers list generation is ok.

**Comment by Jim61C** [comment]
I see. I see. The same problem happens even when I use the command of experiments(1) for only the baseline experiment. May I know which branch and commit you are on? I would like to see of switching to your working branch resolves the problem.

Thank you!

**Comment by alanlukezic** [comment]
I used the release vot2016-final to analyze VOT2016 results.

**Comment by Jim61C** [comment]
Cool, I will give a try.

**Comment by Jim61C** [comment]
Unfortunately, I am still having the same problem :(. Even when I checkout to the vot2016-final tag for the toolkit. Which trackers are you running against? I am wondering if there is anything wrong with the raw results (vot2016_results.zip). Thank you!

**Comment by Jim61C** [comment]
Good news!!! is that after I hand picked some top performing trackers instead of using the entire 'results/trackers.txt', I get the ranking results. However, I come across this error 

In an assignment  A(:) = B, the number of elements in A and B must be the same

Error in report_article (line 124) 
experiments_ranking_data(1:i:end) = scores(:, :, i);

When writing the expected overlap table.

Do you have any idea how to solve this?

Thank you!

**Comment by alanlukezic** [comment]
I used all trackers that are packed in the vot2016_results.zip, without HCF tracker. If you still got an error, I would recommend that you delete all cached files and reports from your current workspace. Additionally, please stop with a breakpoint where the error occurs and try to identify what (which tracker, at which sequence) causes an error.

**Comment by Jim61C** [comment]
Thanks for the advices! I ended up hand-picking the top performing trackers and ran it with the custom correction for the syntax. It worked in generating the report.
