### ISSUE TITLE
Does TraX need to be installed independently(before using vot toolkit)?

### ISSUE THREAD

**Issue by Napcatola** [votchallenge/vot-toolkit#106]
I refer to 'Tutorials and guides '(http://votchallenge.net/howto/) to 'set up the workspace' and 'integrate a 'tracker'.I take **python_ncc.py**(vot-toolkit\tracker\examples\python\python) as my tracker temporarily.

**BUT** there was something wrong when 'run_test' ran.It always stagnates for a long time on line106 in 'trax_test'.   (Matlab 2014b, window8 x64, interpreter used in tracker :python2.7+anaconda2)

` if is_octave()

        [status, output] = system(command, 1);
    else

		if verLessThan('matlab', '7.14.0')
		    [status, output] = system(command);
        else
		    [status, output] = system(command, '');           **(line 106   trax_test)**
		end;
    end;`

Thanks for visiting my question.

**Comment by lukacu** [comment]
TraX should be downloaded when the toolkit is run for the first time. If run_test waits for a long time this typically means that the tracker has blocked the output because of some reason. This is really strange since usually the tracker crashes immediately if something is wrong. What happens if you run the tracker outside the toolkit as a standalone python script?

**Comment by Napcatola** [comment]
Will TraX be  downloaded automatically?or I need install it following the TraX Tutorials(http://trax.readthedocs.io/en/latest/tutorials.html) first?

It always stagnates in that line 
 `[status, output] = system(command, '');           **(line 106   trax_test)**` 
 even though  I skip the 'trax_test'.





————————————run the tracker outside the toolkit——————————————
Debug Stoped at  the line of python_ncc.py :   `handle = vot.VOT("rectangle")`

`F:\anaconda2\python.exe "F:/python project/trackerNCC/python_ncc.py"
@@TRAX:hello "trax.image=path" "trax.region=rectangle" "trax.version=1"`

**Comment by lukacu** [comment]
Yes, TraX is downloaded automatically if used within the toolkit, at least the version that works with it. The TraX library has undergone several changes in the past months and we have to check if the new version still works with the toolkit. This will be ready for the next challenge.

Well the output of the tracker as run outside the toolkit looks fine, it emits TraX hello message and waits for the toolkit (which is not running it so it will wait indefinitely). I must say that this looks strange, can you please modify test_trax.m to print the `command` variable before the problematic line?

**Comment by Napcatola** [comment]
Thank you for your patience.


————————run_test—————disp(command) in test_trax.m—————————————

`"E:\Matlab project\vot-toolkit\native\traxclient.exe" -Q -t 30 -e "TRAX=1" -- "F:\python27\python.exe"  -c "import sys; sys.path.append('E:\Matlab project\vot-toolkit\native\python');sys.path.append('E:\Matlab project\vot-toolkit\vot-workspace'); import python_static"`

———————————————————————————————————————————
I try to modify the 'python_command' part of the `command` from `F:\python27\python.exe` to `F:\anaconda2\python.exe` .BUT nothing changed

**Comment by lukacu** [comment]
Well, as you can see from this command (the path behind --) your tracker is run in a different manner within the toolkit that you were running outside. Can you try pasting this string (so again, the part after --) to command line and see what is the output?

**Comment by Napcatola** [comment]
(python_command="F:\anaconda2\python.exe" )

`e:\Matlab project\vot-toolkit\vot-workspace>"F:\anaconda2\python.exe"  -c "import sys; sys.path.append('E:\Matlab project\
vot-toolkit\native\python');sys.path.append('E:\Matlab project\vot-toolkit\vot-workspace'); import python_ncc"`
`@@TRAX:hello "trax.image=path" "trax.region=rectangle" "trax.version=1"`
————————————————————————————————————————————
(python_command="F:\python27\python.exe" )

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "python_ncc.py", line 6, in <module>
    import cv2
ImportError: DLL load failed: %1 `

————————————————————————————————————————————
I often use `anaconda2/python.exe` with PyCharm.There is no library in `python27\python.exe`.
Should I install some frequently-used lib in it？

**Comment by lukacu** [comment]
Well, the first instance looks ok, in the second case there is likely that the OpenCV is not configured properly because the libraries are not found. Is this output not printed in the log file that is generated during the test run?

In any case, this is hardly a toolkit bug, we can discuss the problem at VOT forum, but I am closing the issue since I cannot fix the problem in the toolkit.

**Comment by Napcatola** [comment]
Thanks a lot~
p.s. The logs/NCC/20170227T095015 folder is blank.
