### ISSUE TITLE
ncc tracker on sequence "iceskater1" in vot2016

### ISSUE THREAD

**Issue by zhengzhugithub** [votchallenge/vot-toolkit#114]
hello, when I run the "run_experiments.m" in vot2016, there is a mistake when processing sequence "iceskater1". I find it is because the value of some groundtruth in this sequence (frame 581 to frame 589) is negtive. 
any solutions? thank you.

**Comment by lukacu** [comment]
While this is not the right place to ask questions regarding the dataset (you can use the forum for this) and I will close the issue, here is an answer: there are multiple cases in the datasets where the groundtruth is outside the image, it is a sign of software robustness that the tracker correctly handles these cases (how this is done depends on the methods used) so I recommend that you e.g. truncate the values correctly.
