### ISSUE TITLE
How to integrate some complex trackers into the vot-toolkit?

### ISSUE THREAD

**Issue by Wanggcong** [votchallenge/vot-toolkit#115]
I followed the instructions http://www.votchallenge.net/howto/workspace.html :
(1) Run toolkit_path.
(2) Go to vot-workspace directory. Run matlab and execute workspace_create command.
(3) Select an experiment stack that you want to use. (have prepared sequence)
(4) Enter the unique indentifier of your tracker, e.g. ccot
(5) Select the interpreter used in your tracker, e.g. matlab.
(6) edit the tracker_xxx.m, e.g. tracker_ccot.m 

CCOT_repo_path = '/home/wang/projects/vot2017/C-COT/Continuous-ConvOp-master';

tracker_label = 'CCOT';
tracker_command = generate_matlab_command('benchmark_tracker_wrapper(''CCOT'', ''VOT2016_settings'', true)', {[CCOT_repo_path '/VOT_integration/benchmark_wrapper']});
tracker_interpreter = 'matlab';
tracker_trax = false;

(7)run the script: run_test.m, choose the action 'b', sequence '1', I got some errors:

Error using system_wrapper>run_once (line 229)
No result produced by tracker. Report written to "/home/wang/projects/vot2017/vot-toolkit-master/workspace/logs/ccot/20170511T090124"

Error in system_wrapper (line 39)
    [Tr, Tm] = run_once(context.directory, tracker, sequence, start, context);

Error in workspace_test (line 90)
            [trajectory, time] = tracker.run(tracker, sequences{current_sequence}, struct('repetition', 1, 'repetitions', 1));

Error in run_test (line 10)
workspace_test(tracker, sequences);

What's wrong with my integration? Thank you!

**Comment by lukacu** [comment]
Well, first of all, you are not using TraX protocol. You will not be able to participate in VOT2017 with the legacy integration approach. It looks like you are using an outdated version of the toolkit. Also, this is not the right place to ask such questions, we have a support forum for this. I am closing the issue.
