### ISSUE TITLE
Unable to create workspace in MATLAB

### ISSUE THREAD

**Issue by pallavivm91** [votchallenge/vot-toolkit#117]
Unable to create workspace in MATLAB. Error: Mex compilation not successful. What should we do to overcome this?

**Comment by lukacu** [comment]
Please do not open new issues with the same problem, this will not help in any way. We will try to pre-compile mex files as we are unable to reproduce your problem.

**Comment by pallavivm91** [comment]
Hi

Sorry for the trouble. Could you please let me know which compiler have you
guys used for this? Because I am successfully able to proceed with vot2016
toolkit using the same compiler but not for vot toolkit 2017.

*I am getting error in the workspace_create -> initialize_native() ->
compile_mex -> and in line 88 of it (mex('-output', name, varargin{:},
includes{:}, files{:}, arguments{:});)*


Else could you please share the contents of the native folder because as
far as my understanding the mex files resides in this.
It will be very helpful if you can help me out of this issue.

Regards
Pallavi
