### ISSUE TITLE
workspace_create error on Mac

### ISSUE THREAD

**Issue by ihpdep** [votchallenge/vot-toolkit#118]
When I create vot 2017 workspace, an error occurs.

Environment: Mac OS 10.12.4 with Xcode Clang++

=================================================================
ERROR: Unable to compile MEX function: "/Users/liyang/Codes/vot-toolkit/native/trax/support/client/client.cpp:113:54: error: invalid operands to binary expression ('__bind<int &, sockaddr *, unsigned long>' and 'int')
        if (bind(sid, (struct sockaddr *)&sin, sizeof(sin)) == -1) {
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~
1 error generated.
".
错误使用 initialize_native (line 82)
Unable to compile all native resources.

出错 workspace_create (line 148)
initialize_native();

**Comment by lukacu** [comment]
Hm, then the API for 10.12 has changed. We have tested it with SDK 10.10 and it compiled ok. Unfortunately I do not have a Mac anywhere near so I cannot debug it, if somebody else can do it it will be fixed sooner.

**Comment by lukacu** [comment]
Actually the problem was very simple, a colleague committed a fix so you are welcome to try it out.

**Comment by ihpdep** [comment]
It works. Thanks a lot.
