### ISSUE TITLE
Issue while creating workspace using for vot toolkit in MATLAB

### ISSUE THREAD

**Issue by pallavivm91** [votchallenge/vot-toolkit#122]
Hi
I am unable to create a workspace using crate_workspace. I am using Visual studio 2012 and my code is in MATLAB.  This issue was already reported and help was obtained from the vot group to close it (https://github.com/votchallenge/vot-toolkit/issues/116#issuecomment-302368667).

However, it is again coming when I am trying it now.
Please have a look, issue is written  below.
------------------------------------error message-----------
Downloading TraX source from "https://github.com/votchallenge/trax/archive/master.zip". Please wait ...
Verifying native components ...
Building with 'Microsoft Visual C++ 2012'.
MEX completed successfully.
Building with 'Microsoft Visual C++ 2012'.
MEX completed successfully.
Building with 'Microsoft Visual C++ 2012'.
MEX completed successfully.
Building with 'Microsoft Visual C++ 2012'.
MEX completed successfully.
Building with 'Microsoft Visual C++ 2012'.
MEX completed successfully.
Building with 'Microsoft Visual C++ 2012'.
MEX completed successfully.
Building with 'Microsoft Visual C++ 2012'.
MEX completed successfully.
Building with 'Microsoft Visual C++ 2012 (C)'.
MEX completed successfully.
Building with 'Microsoft Visual C++ 2012'.
ERROR: Unable to compile MEX function: "trax.c
d:\pallavi\vot-toolkit-master\native\trax\src\buffer.h(153) : warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data
d:\pallavi\vot-toolkit-master\native\trax\src\buffer.h(167) : warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data
d:\pallavi\vot-toolkit-master\native\trax\src\buffer.h(180) : warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(150) : warning C4996: 'strcmpi': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _strcmpi. See online help for details.
        C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE\string.h(248) : see declaration of 'strcmpi'
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(153) : warning C4996: 'strcmpi': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _strcmpi. See online help for details.
        C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE\string.h(248) : see declaration of 'strcmpi'
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(163) : warning C4996: 'strcmpi': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _strcmpi. See online help for details.
        C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE\string.h(248) : see declaration of 'strcmpi'
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(166) : warning C4996: 'strcmpi': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _strcmpi. See online help for details.
        C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE\string.h(248) : see declaration of 'strcmpi'
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(169) : warning C4996: 'strcmpi': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _strcmpi. See online help for details.
        C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE\string.h(248) : see declaration of 'strcmpi'
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(222) : warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(229) : warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(555) : warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _strdup. See online help for details.
        C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE\string.h(241) : see declaration of 'strdup'
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(556) : warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _strdup. See online help for details.
        C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE\string.h(241) : see declaration of 'strdup'
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(557) : warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _strdup. See online help for details.
        C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE\string.h(241) : see declaration of 'strdup'
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(763) : warning C4996: 'fileno': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _fileno. See online help for details.
        C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE\stdio.h(711) : see declaration of 'fileno'
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(764) : warning C4996: 'fileno': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _fileno. See online help for details.
        C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE\stdio.h(711) : see declaration of 'fileno'
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(906) : error C2275: 'string_list' : illegal use of this type as an expression
        d:\pallavi\vot-toolkit-master\native\trax\src\buffer.h(28) : see declaration of 'string_list'
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(906) : error C2065: 'arguments' : undeclared identifier
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(907) : error C2275: 'trax_properties' : illegal use of this type as an expression
        D:\Pallavi\vot-toolkit-master\native\trax\include\trax.h(116) : see declaration of 'trax_properties'
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(907) : error C2065: 'tmp_properties' : undeclared identifier
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(909) : error C2065: 'arguments' : undeclared identifier
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(909) : warning C4047: '=' : 'int' differs in levels of indirection from 'string_list *'
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(910) : error C2065: 'tmp_properties' : undeclared identifier
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(910) : warning C4047: '=' : 'int' differs in levels of indirection from 'trax_properties *'
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(912) : error C2065: 'arguments' : undeclared identifier
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(912) : warning C4047: 'function' : 'const string_list *' differs in levels of indirection from 'int'
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(912) : warning C4024: 'write_message' : different types for formal and actual parameter 4
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(912) : error C2065: 'tmp_properties' : undeclared identifier
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(912) : warning C4047: 'function' : 'trax_properties *' differs in levels of indirection from 'int'
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(912) : warning C4024: 'write_message' : different types for formal and actual parameter 5
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(914) : error C2065: 'arguments' : undeclared identifier
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(914) : warning C4047: 'function' : 'string_list **' differs in levels of indirection from 'int *'
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(914) : warning C4024: 'list_destroy' : different types for formal and actual parameter 1
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(915) : error C2065: 'tmp_properties' : undeclared identifier
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(915) : warning C4047: 'function' : 'trax_properties **' differs in levels of indirection from 'int *'
D:\Pallavi\vot-toolkit-master\native\trax\src\trax.c(915) : warning C4024: 'trax_properties_release' : different types for formal and actual parameter 1

".
Error using initialize_native (line 82)
Unable to compile all native resources.

Error in workspace_create (line 148)
initialize_native();
 --------------------------error completed----------------

**Comment by lukacu** [comment]
Hm, apparently one of the recent changes introduced an incompatibility with some VC++ versions. I have committed a fix, can you please remove the native directory and run the script again?

**Comment by pallavivm91** [comment]
Hi

Yeah its fine now. Thank you for the support.

Regards
Pallavi Venugopal M
