### ISSUE TITLE
Distribute as Matlab Toolbox/Octave Package

### ISSUE THREAD

**Issue by cybertk** [votchallenge/vot-toolkit#130]
As Matlab/Octave both supports install third-party modules in a more user-fridenly and easier way.

For Matlab, distribute as a [Matlab Toolbox][](i.e **vot-toolkit.mltbx**), then user install it by just dragging it into Matlab GUI.

For Octave, distribute as a [Octave Package](i.e. **vot-toolkit.tar.gz**). Then user install it with a single command, `pkg install /path/to/vot-toolkit.tar.gz`

[Matlab Toolbox]: https://www.mathworks.com/help/matlab/matlab_prog/create-and-share-custom-matlab-toolboxes.html#buf2ahi-3
[Octave Package]: https://www.gnu.org/software/octave/doc/interpreter/Creating-Packages.html

**Comment by lukacu** [comment]
Hm, interesting idea. I guess that this would mean that we would have to reorganize some parts of the code but I think that would be nice.

**Comment by lukacu** [comment]
We will not have time to do this for VOT2018, help wanted if somebody is interested.

**Comment by lukacu** [comment]
This will not happen as we are now moving to Python. Closing.
