### ISSUE TITLE
version `CXXABI_1.3.8' not found 

### ISSUE THREAD

**Issue by skyoung** [votchallenge/vot-toolkit#132]
I run this toolkit on Ubuntu 16 with Matlab 2015b. I got the following error message:

```
Tracker execution interrupted: Invalid MEX-file '/home/green/vot-toolkit/native/traxclient.mexa64': /usr/local/MATLAB/R2015b/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/green/vot-toolkit/native/traxclient.mexa64)
TraX support not detected.
```
Could anyone help me figure it out ?

**Comment by skyoung** [comment]
I found a way on the internet to solve it.  `sudo cp /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /usr/local/MATLAB/R2015b/bin/glnxa64/../../sys/os/glnxa64/`.
But still have other problems ref #127

**Comment by lukacu** [comment]
This issue is impossible to solve for all users, the best way is to compile mex files yourself.

**Comment by yipengm** [comment]
@skyoung Thx. Saved me.
