### ISSUE TITLE
Missing .tag in tracker struct

### ISSUE THREAD

**Issue by Timen** [votchallenge/vot-toolkit#134]
I am not exactly sure why this is incorrect, but a lot scripts us the tag field of tracker struct. Maybe this is a mismatch in version of my code but the following line in report_visualization.m gives me an error:

`trackers_styled{t}.tag = sprintf('%s (%.02f), total(%d, %.02f)', trackers{t}.tag
`
This is because the tracker struct does not contain the tag field, it does however contain an identifier so this issue can be easily fixed like this:

`trackers_styled{t}.tag = sprintf('%s (%.02f), total(%d, %.02f)', trackers{t}.identifier
`

I am not sure of all the places where trackers{t}.tag is used but it can be fixed by replacing it with trackers{t}.identifier.

**Comment by lukacu** [comment]
Thanks for the report, some parts of the report generation code have not been used for a long time while we have performed some refactoring ... I will check it out and fix it.

**Comment by lukacu** [comment]
The report_visualization function will be removed in the next version of the toolkit with report cleanup, this makes this issue redundant.
