### ISSUE TITLE
missing images.txt  and region.txt 

### ISSUE THREAD

**Issue by haven0403** [votchallenge/vot-toolkit#139]
I have download vot-toolkit  and DSST tracker (https://github.com/gnebehay/DSST).  and Set up VOT workspace rightly, But I got result as follows :
>> run_test
Initializing workspace ...
Verifying native components ...
Loading sequences ...
Testing TraX protocol support for tracker DSST.
Tracker execution interrupted: Unable to establish connection.
TraX support not detected.
 tracker_load (line 127)
Tracker has not passed the TraX support test.
 run_test (line 8)
tracker = tracker_load('DSST');

when i debug the code ,I found some problem in DSST folder, in the vot_tracker_initialize.m  ,lack of images.txt  and region.txt, how to solve this problem?

**Comment by lukacu** [comment]
The tracker that you are referring to does not support TraX protocol and cannot be used with newer versions of VOT toolkit, it was used only in VOT2014. This is not a toolkit issue, please start a thread on support forum if you want more information.
