### ISSUE TITLE
error using system wrapper>run_once

### ISSUE THREAD

**Issue by haven0403** [votchallenge/vot-toolkit#141]
when i debug run_test.m in linux system with DSST tracker(I download from https://github.com/gnebehay/DSST ),but i encountered the following results:
Experiment baseline
  Tracker DSST
    ***************************************************************************
                         * DEPRECATION WARNING * 
  You are using an outdated mechanism for communication between the tracker
  and the VOT toolkit. Starting with the next version of the toolkit the 
  support for this mechanism will be removed completely. We recommend that
  you switch to TraX protocol before that time to avoid any problems and to
  help us with testing of the protocol.
  ***************************************************************************
    Sequence bag
      Repetition 1
Error using system_wrapper>run_once (line 229)
No result produced by tracker. Report written to "/home/haven/Desktop/vott/vot-toolkit-vot2016-final/vot-workspace/logs/DSST/20171217T205906"
Error in system_wrapper (line 39)
    [Tr, Tm] = run_once(context.directory, tracker, sequence, start, context);
Error in tracker_evaluate (line 108)
            [trajectory, time] = tracker.run(tracker, sequence, context);
Error in workspace_evaluate>execute_iterator (line 101)
            tracker_evaluate(event.tracker, event.sequence, sequence_directory, ...
Error in iterate (line 65)
            context = iterator(event, context);
Error in workspace_evaluate (line 45)
iterate(experiments, trackers, sequences, 'iterator', iterator, 'context', context);

so how to reslove this problem? thank you in advance!

**Comment by lukacu** [comment]
Yes, because the tracker that you are using does not support the new integration protocol. I have said this in #139 already. Please do not post new issues, it is not a toolkit bug. Use our support forum if you want more information or help.
