### ISSUE TITLE
Can not found mexa64 when using the trax

### ISSUE THREAD

**Issue by he010103** [votchallenge/vot-toolkit#143]
Hello, @lukacu ，I want to use mexa64 function in the VOT2017 with trax. However, I found it can not found the function even if I add the path of mexa64.

**Comment by lukacu** [comment]
Hello, please use our [support forum](https://groups.google.com/forum/?hl=en#!forum/votchallenge-help) for questions regarding tracker integration. The issue tracker is only for toolkit bugs and feature requests. Also, please try to describe your situation a bit more, I am currently not sure what you are trying to do.

**Comment by he010103** [comment]
@lukacu Thanks for your answer. I post my question in:
https://groups.google.com/forum/?hl=en#!topic/votchallenge-help/0OjloQV4TJo
