### ISSUE TITLE
Groundtruth format issue concerning Conduction1 sequence in VOT17 dataset

### ISSUE THREAD

**Issue by PeterHuang2015** [votchallenge/vot-toolkit#146]
@lukacu @vojirt @gnebehay 
Hi VOT team, I found the groundtruth file format in newly added `conduction1` sequence is inconsistent with other sequences and manually converted to x1, y1, x2, y2, x3, y3, x4, y4 format; Could it be fixed or its a built-in feature?:monkey:

**Comment by PeterHuang2015** [comment]
![1](https://user-images.githubusercontent.com/13297503/35026031-9f0c1978-fb83-11e7-8393-99d145ab8c33.png)
[groundtruth.txt](https://github.com/votchallenge/vot-toolkit/files/1637747/groundtruth.txt)

**Comment by alanlukezic** [comment]
Hi, VOT toolkit supports both formats: (x0,y0,w,h) and (x0,y0,x1,y1,x2,y2,x3,y3). It automatically detects which format is used in which sequence and converts it to the format you are specifying. If you want manually convert the ground-truth the function region_convert exists in the toolkit.

**Comment by PeterHuang2015** [comment]
Thx alan, got it. just hope that the format could be consistent inside the same dataset.

**Comment by lukacu** [comment]
This issue is not really related to the toolkit itself, we may unify the format at some point, but for now I am closing this issue.
