### ISSUE TITLE
How to get the Accuracy value reported in the VOT17 paper?

### ISSUE THREAD

**Issue by gongbudaizhe** [votchallenge/vot-toolkit#148]
Hi,

The reported performance of KCF at the page 1958 of the [VOT17 paper](http://openaccess.thecvf.com/content_ICCV_2017_workshops/papers/w28/Kristan_The_Visual_Object_ICCV_2017_paper.pdf) is:

tracker | baseline EAO | baseline Accuracy | baseline Robustness | realtime EAO | realtime Accuracy | realtime Robustness
------- | ----------| ------------|-----|---------|--------------| ----
KCF | 0.135  | 0.447  | 0.773 | 0.134 | 0.445 | 0.782

I can get the exactly same number of EAO and Robustness using the [KCF tracker](https://github.com/vojirt/kcf).  EAO can be found in the generated `article.html` file and Robustness can be found by `100 * result.robustness.weighted_mean_normalized` within `report_ranking.m`. However, there is nowhere to get the Accuracy result. 

My question is: how to get the Accuracy value reported in the VOT17 paper? Which script is used to generate these results?

Thanks.

**Comment by lukacu** [comment]
Please use the forum for these kind of questions, issue tracker is for confirmed bugs only.

**Comment by gongbudaizhe** [comment]
Sorry, I didn't know there is a forum for this. It is now asked at [here](https://groups.google.com/forum/?hl=en#!topic/votchallenge-help/CDHxuf6Nab0).
