### ISSUE TITLE
About TraX

### ISSUE THREAD

**Issue by zlj199502** [votchallenge/vot-toolkit#149]
hi,lukacu
‘Tracker has not passed the TraX support test.’
This problem always occurs when I test the tracker on the VOT2016. I test this problem will appear ncc, I wonder why this is?

**Comment by lukacu** [comment]
The problem is most likely due to tracker misconfiguration or linking issue. It is much easier to discuss this kind of issues on our support forum since it is 99.9% chance that this is not a toolkit bug. Please check the if the test produced any log files and if they contain anything.
