### ISSUE TITLE
An error occurs when creating new workspace

### ISSUE THREAD

**Issue by Drdestiny** [votchallenge/vot-toolkit#157]
Hi! I used vot-toolkit to test my Matlab-based tracker. However, after I typed `workspace_create` in command window, it reported an error:
`Downloading TraX source from "https://github.com/votchallenge/trax/archive/master.zip". Please wait
...`
`Warning: directories already exist.`
`> In initialize_native>download_trax_source (line 123)`
`In initialize_native (line 15)`
`In workspace_create (line 148)`
`Unable to unpack TraX source code.`
The new workspace was created, but TraX was not ready. Although I downloaded TraX and compiled it by myself to test my tracker successfully after that, I still want to know why this error occurred.

**Comment by lukacu** [comment]
Yes, this is a known problem because Matlab's urlwrite function cannot handle redirects. Should be fixed in toolkit 6.0 by changing the URL.

**Comment by kingsj0405** [comment]
> The new workspace was created, but TraX was not ready. Although I downloaded TraX and compiled it by myself to test my tracker successfully after that, I still want to know why this error occurred.

Current master failed with this attempt.
When I checkout to commit `d9456064f1b954e37cbd1ad4090bf9ea7d87629f`, it resolved.

```
octave:6> workspace_create
Select one of the available experiment stacks:
 1 - test
 2 - vot2013
 3 - vot2014
 4 - vot2015
 5 - vot2016
 6 - vot2017
 7 - vot2018
 8 - vot2019
 9 - vot2019_rgbd
 10 - vot2019_rgbtir
 11 - votlt2018
 12 - votlt2019
 13 - vottir2015
 14 - vottir2016
Selection: 6
Input an unique identifier for your tracker: VDMR
Is your tracker written in any of the following languages?
  1 - "Matlab"
  2 - "Python"
  3 - "C/C++"
  4 - "Octave"
  5 - "None of the above"
Selected option: 2
Verifying native components ...
/app/sejong/vot-toolkit/native/trax/support/matlab/traxserver.cpp: In function 'void mexFunction(int, mxArray**, int, const mxArray**)':
/app/sejong/vot-toolkit/native/trax/support/matlab/traxserver.cpp:53:45: error: 'custom' declared as reference but not initialized
         std::map<std::string, std::string>& custom;
                                             ^
/app/sejong/vot-toolkit/native/trax/support/matlab/traxserver.cpp:84:22: error: 'class trax::Metadata' has no member named 'set_custom'
             metadata.set_custom(iterator->first, iterator->second);
                      ^
/app/sejong/vot-toolkit/native/trax/support/matlab/traxserver.cpp:180:48: error: expected ',' or ';' before ')' token
             string reason = get_string(prhs[0]));
                                                ^
warning: mkoctfile exited with failure status
ERROR: Unable to compile MEX function: "Compile problem, see compiler output.".
error: Unable to compile all native resources.
error: called from
    initialize_native at line 87 column 5
    workspace_create at line 143 column 1
```

**Comment by lukacu** [comment]
The error should be fixed now. Please delete native folder and rerun.

**Comment by kingsj0405** [comment]
@lukacu Nicely work on master too! Thank you :)
