### ISSUE TITLE
 VOT2018 long-term bechmark evaluation metrics

### ISSUE THREAD

**Issue by zhuangjunfei** [votchallenge/vot-toolkit#159]
Hi lukacu,
The VOT2018 has already started but I cant find any information about VOT2018 long-term bechmark evaluation metrics. Would you please provide me official document about long-term visual tracking evaluation metrics ?
Thanks

**Comment by lukacu** [comment]
We have not always published evaluation metrics in advance, but for long-term tracking you can check our [ArXiv paper](https://arxiv.org/abs/1804.07056).

**Comment by zhuangjunfei** [comment]
Thanks!

**Comment by zhuangjunfei** [comment]
Sorry to bother you again, I try ncc and static on VOT2018 long-term benchmark, and I have already obtain the results from two trackers, but when I run "run_analysis.m",  I get an error like this
Subscripted assignment dimension mismatch.

Error in analyze_precision_recall>calculate_tpr_fscore (line 167)
            certanty(i:i+size(groundtruth{s})-1, r) = values{s, r};

and I find that no "../VOT2018LT/vot-toolkit-master-LT/workspace/results/ncc/longterm/ballet/ballet_001_confidence.value" existence, the problem is how could I get “ballet_001_confidence.value"？
