### ISSUE TITLE
EAO analysis only suitable for supervised experiments

### ISSUE THREAD

**Issue by lawpdas** [votchallenge/vot-toolkit#164]
I get this error `EAO analysis only suitable for supervised experiments` when `run_analysis`.

In `/VOT2018/report/report_expected_overlap.m` line 38, `experiment.type` doesn't support `realtime`.
I change the code from 
```matlab
if ~strcmp(experiment.type, 'supervised')
```
to
```matlab
if ~strcmp(experiment.type, 'supervised') && ~strcmp(experiment.type, 'realtime')
```
Does this affect the result？

**Comment by lukacu** [comment]
No, this is the correct fix, somehow I have missed this when updating analysis code. The fix is not crucial for experiment execution, but I will apply it asap anyway.

**Comment by lukacu** [comment]
Fix in master.
