### ISSUE TITLE
Tag EAO is NaN

### ISSUE THREAD

**Issue by lawpdas** [votchallenge/vot-toolkit#165]
I don’t know why there is only empty tag EAO in baseline and unsupervised report.  Other tag EAO is NaN.

**Comment by lukacu** [comment]
You will have to be more specific, what is the sequence of commands that you run to get to this issue?

**Comment by lawpdas** [comment]
Thanks for your reply!

Follow the tutorial, `run_experiments`, `run_pack`, `run_analysis`

run_analysis.m
```matlab
ddpath('/home/lawpdas/Documents/VOT2018'); toolkit_path; 
[sequences, experiments] = workspace_load();
trackers = tracker_list('rt_tracker.txt','MY'); 
workspace_analyze(trackers, sequences, experiments, 'report_MY', 'Title', 'Report for vot2018');
```

Thanks!

**Comment by lukacu** [comment]
And what is the table that you get? I do not completely understand the issue that you are having.

**Comment by lawpdas** [comment]
Just like this, value is NaN, nothing in plot.
![image](https://user-images.githubusercontent.com/5070053/40052845-972530be-5871-11e8-8066-2ad649dee66c.png)

![image](https://user-images.githubusercontent.com/5070053/40052882-c9888e52-5871-11e8-867c-f06042ef7faa.png)


![image](https://user-images.githubusercontent.com/5070053/40052773-619d7f50-5871-11e8-9568-334377b18ad8.png)

**Comment by lukacu** [comment]
There was a bug when loading sequences, the names of the properties were not correctly decoded which resulted in NaNs. We have fixed this in master branch.

**Comment by lawpdas** [comment]
I see the `usetags`  in `report_expected_overlap.m` is false. So the EAO on tags are not important to vot2018? Sorry, I don't know much about vot challenge.

**Comment by LCAR979** [comment]
Just leave a note: We also find many values of 0.0  in EAO evaluation under different tags using the version #784791d. After pulling from master just now, forwarding to #ee3c65e, they go away.

**Comment by lukacu** [comment]
We have disabled per-tag calculation because I have to review if it even works correctly. While it is true that we had implemented it at some point, it is not that important for the overall analysis, it is better to use EAO for the entire dataset and evaluate performance on individual properties using A-R analysis.
