### ISSUE TITLE
Need a latest official releases of the toolkit

### ISSUE THREAD

**Issue by Kewenjing1020** [votchallenge/vot-toolkit#166]
Hello @lukacu, can you provide a lastest official release of the toolkit? The link in ReadMe is invalid, I would like to retry with the lastest version.

**Comment by lukacu** [comment]
Hm, which readme is invalid? Most common way of downloading the toolkit is by simply getting a ZIP from Github, we also have some [pre-built packages](https://bintray.com/votchallenge/toolkit/current/6.0.0), but they are not as up-to-date.

**Comment by Kewenjing1020** [comment]
I couldn't load this link:

> Click here to browse and download the latest official releases of the toolkit.

**Comment by lukacu** [comment]
If you go to the tab "Files" you will find the files. Please ask such question on our support forum, Github is for bugs in the code and feature requests.
