### ISSUE TITLE
fail to run the tracker from VOT2017 Trackers repository

### ISSUE THREAD

**Issue by Kewenjing1020** [votchallenge/vot-toolkit#167]
Hello @lukacu , I have successfully run the 'ncc' tracker on Windows and Linux. While I downloaded the SiameseFC code from [](http://votchallenge.net/vot2017/trackers.html), I copied the tracker_SiamFC.m file to vot-workspace and modified the line of tracker_command as the code instructed:

`tracker_command = generate_matlab_command('run_baseline5_VOT', {'/Users/wenjing-work/Documents/workspace/siamfc_vot/cf_net/src/tracking});`

And I get the error as follows:

> Testing TraX protocol support for tracker siamesefc.
/home/kewenjing/vot/vot-toolkit-vot2016-final/native/traxclient -Q -t 30 -e "TRAX=1" -- /home/kewenjing/software/Matlab_linux/install/bin/matla
b -nodesktop -nosplash -r "try; diary 'runtime.log'; addpath('/home/kewenjing/vot/siamfc_vot/cfnet/src/tracking');addpath('/home/kewenjing/vot/
vot-toolkit-vot2016-final/native/mex');run_baseline5_VOT; catch ex; disp(getReport(ex)); quit; end;": Segmentation fault
TraX support was not detected. Debug information saved to directory /home/kewenjing/vot/vot-toolkit-vot2016-final/vot-workspace/logs/siamesefc/
20180514T204631

***************************************************************************

Warning: TraX protocol was not detected using automatic test.
This means that the tracker either does not support the protocol or there
was the error in the configuration. In the first case please set tracker_trax
variable to false in your tracker description file to manually disable testing.
In the second case investigate the error logs to determine the cause of the.
error.

**Comment by Kewenjing1020** [comment]
Oh, I just fixed the problem by modifying the path setup.

**Comment by xi-mao** [comment]
How did you solved the problem
