### ISSUE TITLE
running result unstable: Unable to contact tracker.

### ISSUE THREAD

**Issue by Kewenjing1020** [votchallenge/vot-toolkit#168]
hello @lukacu , after I succeed to run 'ncc' and siamesefc,  I met strange problems:

At the beginning, I modified the 'list.txt' to include less sequences. After I have successfully setup the tracker, I want to run all the sequences, so I replaced the 'list.txt' with its original version. But it still runs the very few sequences, seems like the modification of 'list.txt' making no sense.

And in order to run all the sequences, I create another vot-workspace and set the tracker_xxx.m as the previous one, then some thing strange occurs: 

1. when I run 'run_test', it still offers the very few sequences for me to choose. like 

> Choose a sequence:
  1 - "bag"
  2 - "motocross1"
  3 - "motocross2"

2. I cannot run the tracker anymore, even 'ncc':

> @@TRAX:hello "trax.image=path;" "trax.region=rectangle;" "trax.version=1" 
@@TRAX:initialize "file:///home/kewenjing/vot/vot-toolkit-vot2016-final/vot-workspace/sequences/bag/00000001.jpg" "291.8300,124.7100,150.3400,139.5800" 
@@TRAX:state "291.8300,124.7100,150.3400,139.5800" 
@@TRAX:frame "file:///home/kewenjing/vot/vot-toolkit-vot2016-final/vot-workspace/sequences/bag/00000002.jpg" 
Error: Unable to contact tracker.

Could you please give me some sign why could this happen?

**Comment by lukacu** [comment]
I am not sure about the second problem, it will require more information, but the first one is probably caused by the toolkit caching sequences, you have to clear the workspace (clear all) to force the toolkit to reload them.

**Comment by Kewenjing1020** [comment]
I clear all the other workspace and it works! Thanks! @lukacu
