### ISSUE TITLE
How to use run_analysis for realtime results?

### ISSUE THREAD

**Issue by Mason-J** [votchallenge/vot-toolkit#169]
Sorry to bother @lukacu but I encounter a problem when I run run_analysis for realtime results.

I find realtime.type = 'realtime' in line 29 in stack_vot2018;

When run the function report_expected_overlap, it will show 'EAO analysis only suitable for supervised experiments!'.

if ~strcmp(experiment.type, 'supervised')
   error('EAO analysis only suitable for supervised experiments!');
end

**Comment by lukacu** [comment]
This was fixed in one of the recent commits, please check existing issues before opening new ones: #164.
