### ISSUE TITLE
may be some wrong annotations

### ISSUE THREAD

**Issue by zhuangjunfei** [votchallenge/vot-toolkit#172]
Hi
I doubt may be some wrong annotations in VOT2018 long-term. May I spare your several minutes for checking the  annotation from row 540 to 543 on 'longboard' sequence. Thanks

**Comment by alanlukezic** [comment]
Hi,
thank you for pointing this out. It seems that some annotations are out-of-frame. We will check this and fix it before analysis will be made.

**Comment by lukacu** [comment]
This is a dataset issue, we will fix it, but closing the issue since it is not relevant to the toolkit itself.
