### ISSUE TITLE
why the results of VOT17 or VOT18 are  different? different annotation?

### ISSUE THREAD

**Issue by 110awesome** [votchallenge/vot-toolkit#174]
Hi，we get different vot17 results with the old vot2017toolkit and new vot2018toolkit

**Comment by he010103** [comment]
I met the same question.

**Comment by alanlukezic** [comment]
Hi, where did you observe the difference (sequence, frame)? Did you check the output (raw files with bounding-boxes)? Is the output of the VOT18 the same as VOT17?

**Comment by 110awesome** [comment]
thank you！I find why different the vot17 results on newest version vot-toolkit and vot17 released version. because of the limitation of singleCompThread. Can I remove the limitation? 
![image](https://user-images.githubusercontent.com/20498205/40920408-04e452d8-683f-11e8-9eaa-ce4664e964f4.png)

**Comment by alanlukezic** [comment]
The single-thread limitation is now removed from the toolkit. You should run your tracker again using the latest version of the toolkit. Thank you for pointing out this issue!

**Comment by 110awesome** [comment]
Thank you very much!
