### ISSUE TITLE
The question about vot2018

### ISSUE THREAD

**Issue by he010103** [votchallenge/vot-toolkit#175]
Hi, @bjanssen . Is the groundtruth of vot2018 different from the vot2017? I use the same code of my tracker. But the results of newly vot-toolkit is different from that of the vot2017 in release.

**Comment by alanlukezic** [comment]
Hi, groundtruth for the VOT18 main (short-term) challenge is the same as VOT17. Can you be more specific about the differences? In which sequence, frame, which experiment? Which tracker do you test? Is it deterministic?

**Comment by he010103** [comment]
https://github.com/votchallenge/vot-toolkit/issues/174 The tracker of mine diff when using single thread. Can I submit the tracker which can only be tested in the multithreading envrionment?

**Comment by alanlukezic** [comment]
Does this happen only in realtime experiment or also in baseline?

**Comment by he010103** [comment]
it happen also in baseline!

**Comment by alanlukezic** [comment]
Ok, we will investigate this and make it clear as soon as possible. Can all of you who has this problem tell us which trackers are you testing?

**Comment by he010103** [comment]
I am testing a new version of CFWCR.

**Comment by alanlukezic** [comment]
We have now removed single-thread flag for Linux in the toolkit. You should run your tracker again with this setup. Thank you for reporting this issue!

**Comment by lawpdas** [comment]
@alanlukezic Need I run my tracker again with new version toolkit? Does this flag change the results of other trackers?

**Comment by alanlukezic** [comment]
I think that it is not needed.
