### ISSUE TITLE
Is there a way to use vot toolkit without trax?

### ISSUE THREAD

**Issue by huanglianghua** [votchallenge/vot-toolkit#176]
Hi, thanks for the toolkit. But when I was using vot toolkit to evaluate several trackers, for a large number of trackers the toolkit reported "not receive response", even if I have set the timeout to 300000, and tested that the trackers work OK outside the toolkit.

So, I wonder if there's a way to run the toolkit WITHOUT the trax server and client communication, but rather directly input the `init` and `update` functions of a tracker to run the results? In this way, no communication errors would ever occur? Thanks.

**Comment by alanlukezic** [comment]
Hi, currently the communication between the tracker and toolkit is supported only via trax protocol.
