### ISSUE TITLE
Error in running analysis for long-term tracking

### ISSUE THREAD

**Issue by HengCVer** [votchallenge/vot-toolkit#177]
Hi, dear authors,

Recently, I tried the VOT long-term tracking challenge. I could successfully run the tracker and get the tracking results by running 'run_experiments.m'. After that, I tried to analyze the results and just ran 'run_analysis.m'. Just got the following errors:

run_analysis
Initializing workspace ...
Verifying native components ...

ECO_repo_path =
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

Experiment redetection
  Analysis overlap
    Writing overlap table ...
  Analysis speed
Experiment longterm
  Analysis precision_recall
    Tracking precision-recall analysis for experiment longterm ...
      Tracker XXX
Subscripted assignment dimension mismatch.

Error in analyze_precision_recall>calculate_tpr_fscore (line 167)
            certanty(i:i+size(groundtruth{s})-1, r) = values{s, r};

Error in analyze_precision_recall (line 69)
            [curves, fmeasure] = calculate_tpr_fscore(selectors{s},
            experiment, trackers{i}, experiment_sequences,
            thresholds);

Error in document_cache (line 26)
    result = fun(varargin{:});

Error in report_precision_recall (line 61)
result = document_cache(context, cache_identifier,
@analyze_precision_recall, experiment, trackers, ...

Error in workspace_analyze (line 65)
        [document, scores] = report_function(context, experiment,
        trackers, sequences, analysis.parameters{:});

Error in run_analysis (line 13)
workspace_analyze(trackers, sequences, experiments, 'report_ECO',
'Title', 'Report for votlt2018');

I tried many times but still got no idea. Could you please help check my errors?

Thanks a lot!

Best,

**Comment by HengCVer** [comment]
Hi, Alan,

Thanks a lot for your reply. It seems that I did not report the confidence score.

**Comment by HengCVer** [comment]
By the way, what is the range for the confidence score, like [0, 1], or other ranges?

**Comment by alanlukezic** [comment]
The toolkit does not specify the confidence score range.

**Comment by lukacu** [comment]
I assume this works now, closing.
