### ISSUE TITLE
run_analysis on redetection issue

### ISSUE THREAD

**Issue by zhanglichao** [votchallenge/vot-toolkit#180]
Does anyone know the errors:

Subscript indices must either be real positive integers or logicals.

Error in sequence_test_redetection (line 41)
    redetection_image(y0:y1, x0:x1, :) = target_template;

Error in stack_votlt2018>@(sequence)sequence_test_redetection(sequence,'Length',200,'Initialization',5,'Padding',2,'Scaling',3) (line 16)
redetect.converter = @(sequence) sequence_test_redetection(sequence, ...

Error in convert_sequences>convert_sequence (line 50)
    sequence = converter(sequence);.....

**Comment by lukacu** [comment]
No reply so closing the issue.
