### ISSUE TITLE
A little bug in reporting (normalized) speed for long-term challenge

### ISSUE THREAD

**Issue by HengLan** [votchallenge/vot-toolkit#182]
Hi, dear authors,

when running run_analysis for the long-term challenges, it seems there is an error in the report_speed.m (line 63) if there is only one tracker to be analyzed. If we only analyze one tracker, the variable 'speed.normalized' will be like [1x1x35] and the 'averaged_normalized' will be like [1x1]. When executing line 63 in report_speed.m, an error will occur in call the matlab function 'cat' because of 'the dimensions do not match', which is because 'squeeze([1x1x35])' will get the result of '[35x1]' here instead of '[1x35]'. Thus, one needs to transpose '[35x1]' to '[1x35]'. 

However, if you analyze two or more trackers, there will be no error, because 'squeeze([1x2x35])' will get the result of '[2x35]'. I fix it as follows:

_if numel(averaged_normalized) > 1
        tabledata = num2cell(cat(2, squeeze(speed.normalized), averaged_normalized'));
else
        tabledata = num2cell(cat(2, squeeze(speed.normalized)', averaged_normalized'));
end_

I am not sure if this error only happens in my side. You could check it on your side by running analysis for only one tracker.

Best

**Comment by alanlukezic** [comment]
Thank you for reporting this bug. We will focus on the analysis part in the following weeks and update the toolkit then.

**Comment by lukacu** [comment]
@alanlukezic, can you check if we have addressed this?
