### ISSUE TITLE
Using Trax with Windows - Trax Support and TraxClient Connection

### ISSUE THREAD

**Issue by DEUCE1957** [votchallenge/vot-toolkit#183]
I have attempted for some time now to resolve this issue based on responses to `[#127](https://github.com/votchallenge/vot-toolkit/issues/127)` and [#34](https://github.com/votchallenge/trax/issues/34) under Trax but without success.

After setting up the Workspace, I attempt to Intregrate the NCC example tracker. From examining the error message, I can say the error is thrown inside the **tracker_test.m** script. I have also installed the [Trax](https://github.com/votchallenge/trax) support library seperately [using Cmake](http://trax.readthedocs.io/en/latest/tutorial_windows.html) and have the trax\bin folder listed under my environmental variables.

I have put diagnostic print messages inside of the script, and it appears the
`if exist(cache_file, 'file')` (line 29, tracker_test.m) 
stament does not pass. 

The try statement is also executed but is caught at:
`data = tracker_run(tracker, @callback, data);`
Whereafter the support is said not to be detected.
 
![image](https://user-images.githubusercontent.com/35366296/42504487-e4cb482e-8433-11e8-89b2-ffa0e3c1a3e2.png)
 
**System Details**
OS: Windows 10
Visual Studio: 2015 (version 14)
Matlab: 2017b
Toolkit :: Major: 6 Minor: 0 Patch: 3 (6.0.3)

Any assistance would be greatly appreciated especially as I am wishing to test some of the VOT2017 trackers and cannot proceed if the toolkit is not working.

---- UPDATE 11/07/2018 ----
**Trax Support is now detected** however when attempting to the run the NCC example tracker, the Trax Client does not receive a response. The connection is otherwise succesfully established.
![image](https://user-images.githubusercontent.com/35366296/42572002-8f25d668-8510-11e8-9f93-d5de0ccbbd5d.png)

**Comment by xi-mao** [comment]
have you solved the problem？

**Comment by lukacu** [comment]
From what I can see in the screenshots (please do not post them anymore, we prefer text logs), the tracker starts but times out at the first frame. A common reason for this is that the tracker needs too much time to initialize in which case you have to increase the timeout period. There are a lot of threads on how to do this. The other option is that the tracker has crashed.

**Comment by MSathishkumar1990** [comment]
I am also getting the same error. kindly help me to solve this issue.
