### ISSUE TITLE
Error in run_analysis for workspace_analyze ?

### ISSUE THREAD

**Issue by lyv023** [votchallenge/vot-toolkit#184]
Thanks for giving help
When I run the run_analysis.m and get a problem as follow: 

Experiment baseline
Reference to non-existent field 'analysis'.

Error in workspace_analyze (line 42)
    analyses = convert_metadata(experiment.analysis);

Error in run_analysis (line 13)
workspace_analyze(trackers, sequences, experiments, 'report_NCC', 'Title', 'Report for test');

Thanks

**Comment by WWWangJie** [comment]
Hello! Have you solve this question?

**Comment by lyv023** [comment]
Not yet,
I look into the code and change lots of things, but it is far away to do that.
So I decide to use the old version. But I still waiting for the resolution.

**Comment by WWWangJie** [comment]
Thanks for your reply,
I'm using vot-toolkit for the first time, I have tried several versions, all of them have some problems.
So can you tell me the version that you are employing? 
If it is convenient, could you please provide it.

**Comment by lukacu** [comment]
Can you please specify which experiment stack are you using. The error is really strange, it looks like you are using an unmaintained stack file that does not contain analysis specification.

**Comment by lukacu** [comment]
I am still waiting for a reply, without the details I cannot reproduce the problem.

**Comment by lyv023** [comment]
Thanks for replying
I download the newest version vot-toolkit and generate the graph successfully. It was amazing and I don't know why it would occur that problem before. Nevermind, Thanks again.

**Comment by lukacu** [comment]
Apparently yes.

**Comment by hjjlovecyy** [comment]
@lyv023 Hello, could u give me email. I have faced this problem for a long time. But I can't solve it even if I change the version of vot-toolkit

**Comment by hjjlovecyy** [comment]
@WWWangJie @shuaishentao Hello, have u solved this problem. If it is convenient, could you please provide it. Thank u a lot.

**Comment by HilmiK** [comment]
I am still facing with the same issue with current version of toolkit.

**Comment by MZYGSX** [comment]
I am still facing with the same issue with current version of toolkit.But I can't solve it even if I change the version of vot-toolkit.

**Comment by MZYGSX** [comment]
> 
> 
> Not yet,
> I look into the code and change lots of things, but it is far away to do that.
> So I decide to use the old version. But I still waiting for the resolution.
I also have  met this problem. Could you give me an old version? Thank you！

**Comment by MZYGSX** [comment]
> 
> 
> Not yet,
> I look into the code and change lots of things, but it is far away to do that.
> So I decide to use the old version. But I still waiting for the resolution.

I also have met this problem. Could you give me an old version? Thank you！
