### ISSUE TITLE
Error using cat, in report_speed.m

### ISSUE THREAD

**Issue by lzw19951010** [votchallenge/vot-toolkit#189]
Hi, I'm now integrating a new tracker with vot-toolkit's python wrapper.
After I run_experiments for all the dataset, I executed the command run_analysis and error occurs during speed analysis.

backtrace:
```
Analysis speed
Error using cat
Dimensions of matrices being concatenated are not consistent.

Error in report_speed (line 63)
    tabledata = num2cell(cat(2, squeeze(speed.normalized), averaged_normalized'));

Error in workspace_analyze (line 65)
        [document, scores] = report_function(context, experiment, trackers, sequences, analysis.parameters{:});

Error in run_analysis (line 13)
workspace_analyze(trackers, sequences, experiments, 'report_XXX', 'Title', 'Report for vot2018');
```

Then I dived into the code, and made several changes to the usage of cat in report_speed.m
Now I can successfully execute the run_analysis command, but I'm not quite certain about the change. It would be nice if you could review my pull request( #190 )! Thank you!

**Comment by lukacu** [comment]
Closing issue, fix has been merged.
