### ISSUE TITLE
Test a ECO tracker written in C++ always get "Did not receive response" error

### ISSUE THREAD

**Issue by rockkingjy** [votchallenge/vot-toolkit#191]
I am trying to test the ECO tracker written in C++ here: https://github.com/rockkingjy/OpenTracker
and test it with vot-toolkit and trax, but after success run on a few datasets, it always have the following errors like this:
```
>> run_experiments
Initializing workspace ...
Verifying native components ...
Experiment baseline
  Tracker ECOCPP
    Sequence ants1
    Sequence ants3
      Repetition 1
      Tracker execution interrupted: Did not receive response.
Error using traxclient
Did not receive response.
Error in tracker_run (line 77)
    data = traxclient(tracker.command, callback, ...
Error in experiment_supervised (line 71)
    data = tracker_run(tracker, @callback, data);
Error in tracker_evaluate (line 57)
	[files, metadata] = experiment_function(tracker, sequence,
        directory, parameters, scan);
Error in workspace_evaluate>execute_iterator (line 128)
            tracker_evaluate(event.tracker, event.sequence,
            event.experiment);
Error in iterate (line 65)
            context = iterator(event, context);
Error in workspace_evaluate (line 93)
context = iterate(experiments, trackers, sequences, 'iterator',
iterator, 'context', context);
Error in run_experiments (line 10)
workspace_evaluate(tracker, sequences, experiments);
```
could you help me how to debug this out?

**Comment by lukacu** [comment]
It looks like the tracker has crashed, did you check the log file?

**Comment by lukacu** [comment]
I am not sure what do you mean, logfile is a normal text file located in the logs folder + your tracker identifier. Also it is hard to guess what may be the reason for a crash, apparently it works for sequence ants1, so it may be that it is a memory access error or some other stochastic reason.

**Comment by rockkingjy** [comment]
Thanks for your response, I think I've found the reason for the error, it's my tracker crashed.
