### ISSUE TITLE
tracker not alive

### ISSUE THREAD

**Issue by WWWangJie** [votchallenge/vot-toolkit#193]
When I use vot to test the eco tracker, I have encountered the strange problem that the tracker not alive.
I hope you can solve my problem

**Comment by WWWangJie** [comment]
Tracker execution interrupted: Tracker process not alive anymore
错误使用 traxclient
Tracker process not alive anymore

**Comment by xjtuwh** [comment]
你好，我也遇到了同样的问题，请问你解决了吗？@WWWangJie

**Comment by WWWangJie** [comment]
not yet, I have changed the version, and the problem don't exit anymore.

**Comment by xjtuwh** [comment]
Okay, thanks you anyway~

**Comment by xjtuwh** [comment]
I use the latest version from github. I want to know which version you use and How can I get old version?@WWWangJie

**Comment by WWWangJie** [comment]
The version I used is the vot-toolkit-master, but I don't remember the detail, you can try other version from github

**Comment by xjtuwh** [comment]
Okay, thanks again~

**Comment by lukacu** [comment]
Probably not relevant anymore, in any case not enough information.
