### ISSUE TITLE
Error when running run_test.m with Octave on Ubuntu

### ISSUE THREAD

**Issue by UndecidedBoy** [votchallenge/vot-toolkit#199]
Hello,

I get the following Error when trying to run_test.m on the python_ncc.py tracker provided from the example folder (_The VOT Workspace is created for python tracker using the tutorial from the challenge, also followed the steps for integration of python tracker_):

---
- _Error_:
octave:1> run_test
Initializing workspace ...
Verifying native components ...
Loading sequences ...
error: sequence_create: Invalid resizing operation or ambiguous assignment to an out-of-bounds array element
terminate called after throwing an instance of 'octave::execution_exception'
fatal: caught signal Aborted -- stopping myself...
Aborted (core dumped)
---
- _Which is caused by_:
In sequence_create.m
Line 86: sequence.groundtruth = read_trajectory(fullfile(sequence.directory, sequence.file));
I presume that this is due to a MEX compatibility issue with Octave, but I'm not sure...
---
- _My setup_:
OS: Running Ubuntu 16.04.5 LTS, 64 bits as a Virtual Machine.
VOT-Toolkit: toolkit-6.0.3-linux64.
Octave: Octave-4.4.1 build from source with all the packages needed plus the Octave Forge packages.
----

Every help is appreciated :)

_P.S._: Could this error come from my Octave version? If so, which Octave version or Ubuntu version worked with the Toolkit?

**Comment by lukacu** [comment]
We have only tested Octave support for version 4.0, so that may be the reason. Have you compiled mex files yourself or have they been downloaded?

**Comment by UndecidedBoy** [comment]
Thank you for your answer :)

Can't remember now for the mex files but I don't recall downloading them, but I'll try again using version 4.0 of Octave and follow again the tutorial.
