### ISSUE TITLE
Strange Crash when running pytorch 0.2.0, 0.3.1

### ISSUE THREAD

**Issue by skyoung** [votchallenge/vot-toolkit#200]
`@@TRAX:hello "trax.image=path" "trax.region=rectangle" "trax.version=1"
CLIENT: Tracker process ID: 7268
CLIENT: Connection with tracker established.
@@TRAX:initialize "file:///home/visal/vot-toolkit-new-lup/vot2016-workspace/sequences/bag/color/00000001.jpg" "292.2300,128.3600,145.9600,132.4700" 
@@TRAX:status "292.23,128.36,145.96,132.47"
@@TRAX:frame "file:///home/visal/vot-toolkit-new-lup/vot2016-workspace/sequences/bag/color/00000002.jpg" 
CLIENT: Timeout reached. Stopping tracker process ...
CLIENT: Trying to stop process using protocol.
@@TRAX:quit 
CLIENT: Trying to terminate process nicely.
CLIENT: Flushing streams

CLIENT: Process should be terminated.
CLIENT: Stopping logger.
CLIENT: Tracker exited (stopped by signal 15)
CLIENT: Trying to stop process using protocol.
CLIENT: Cleaning up.
CLIENT: Stopping logger thread
CLIENT: Stopping watchdog thread
CLIENT: Trying to stop process using protocol.`

I running my tracker which is written in pytorch 0.3.1, It always fail when integrating VOT. Above is the log informaiton. Could anynone have any idea?

**Comment by lukacu** [comment]
Well, there is the "timeout reached" hint, the tracker probably needs a lot of time to process a single frame which causes the toolkit to terminate it, you can try increasing the timeout, there are plenty of thready on how to do this on our forum.
