### ISSUE TITLE
Unable to establish connection on Ubuntu 16.04

### ISSUE THREAD

**Issue by addvaluejack** [votchallenge/vot-toolkit#201]
Hello,

I am using Ubuntu 16.04 + Matlab R2016b + gcc 5.4. I successfully run "create_workspace.m". Then I tried the matlab example provided in "tracker/examples/matlab" but failed. 

I have modified "tracker_ncc.m" file like this:

```
tracker_label = [];
tracker_command = generate_matlab_command('ncc', {'/home/username/Repo/vot-toolkit/tracker/examples/matlab'});
tracker_interpreter = 'matlab';
```

The error code displayed in matlab looks like this:

```
Initializing workspace ...
Verifying native components ...
Testing TraX protocol support for tracker ncc.
Tracker execution interrupted: Unable to establish connection.
TraX support not detected.
错误使用 tracker_load (line 127)
Tracker has not passed the TraX support test.

出错 run_test (line 8)
tracker = tracker_load('ncc');
```

Could anyone give me some advice or hint about solving this problem? Thank you very much.

**Comment by xjtuwh** [comment]
你好，我也遇到了这个问题，请问你解决了吗？

**Comment by addvaluejack** [comment]
> 你好，我也遇到了这个问题，请问你解决了吗？

Hello, this is problem is still unsolved.

**Comment by xjtuwh** [comment]
嗯，重新从GitHub上下载一个vot套件，重新编译trax

**Comment by amandayeyan** [comment]
Try python 2.7, may solve the issue.

**Comment by xi-mao** [comment]
@addvaluejack  have you solved the problem? I need help

**Comment by xi-mao** [comment]
@xjtuwh  请问你的python_ncc怎么解决的

**Comment by lukacu** [comment]
Ok, unfortunately I do not understand much of this thread, since this is an issue (communication between users and developers) I am closing it. But you can open a thread on our support forum and continue.

**Comment by xjtuwh** [comment]
I have solved  this problem by modify the connection method in tracker_run.m as 'socket'
% Hint to tracker that it should use trax
environment.TRAX = '1';

connection = 'socket';
