### ISSUE TITLE
run_analysis error

### ISSUE THREAD

**Issue by hjjlovecyy** [votchallenge/vot-toolkit#203]
References to field that do not exist 'analysis'。
error workspace_analyze (line 42)
analyses = convert_metadata(experiment.analysis);
error run_analysis (line 13)
workspace_analyze(trackers, sequences, experiments, 'report_NCC', 'Title', 'Report for test');

It seems that  there is no field named 'analysis' in variable experiments  in run_analysis.m.
I don't know how to solve it.
Thank u.

**Comment by amandayeyan** [comment]
Anyone solved this issue? I am facing the same error.

**Comment by youyouyudi** [comment]
The same problem,  the variable experiments is generated in stack_test.m, and there is no element analysis.
`function experiments = stack_test()

set_global_variable('bundle', 'http://data.votchallenge.net/toolkit/test.zip');

baseline.name = 'baseline';
baseline.converter = [];
baseline.type = 'supervised';
baseline.tags = {'camera_motion', 'illum_change', 'occlusion', 'size', ...
    'motion', 'empty'};
baseline.parameters.repetitions = 5;
baseline.parameters.burnin = 10;
baseline.parameters.skip_initialize = 5;
baseline.parameters.failure_overlap = 0;

realtime.name = 'realtime';
realtime.converter = [];
realtime.type = 'realtime';
realtime.tags = {'camera_motion', 'illum_change', 'occlusion', 'size', ...
    'motion', 'empty'};
realtime.parameters.repetitions = 5;
realtime.parameters.burnin = 10;
realtime.parameters.skip_initialize = 5;
realtime.parameters.failure_overlap = 0;
realtime.parameters.fps_override = true;
realtime.parameters.fps_default = 20;

experiments = {baseline, realtime};

end`

**Comment by lukacu** [comment]
Hm, so you have used testing stack and tried to run analysis on this ... this stack was probably missed when we added the functionality, but I will fix it.

**Comment by AHUgaoyuan** [comment]
I am facing the same problem！How to solve this problem? Thank you

**Comment by MZYGSX** [comment]
I also met the same question, but i don't know how to solve it.

**Comment by AHUgaoyuan** [comment]
> I also met the same question, but i don't know how to solve it.

I have solved it !

**Comment by MZYGSX** [comment]
so can you tell me how to solve it? Thank you!

> 
> 
> > I also met the same question, but i don't know how to solve it.
> 
> I have solved it !

so can you tell me how to solve it? Thank you!

**Comment by MZYGSX** [comment]
> 
> 
> Anyone solved this issue? I am facing the same error.

Have you solved this problem? If so, how to solve it?

**Comment by AHUgaoyuan** [comment]
> > Anyone solved this issue? I am facing the same error.
> 
> Have you solved this problem? If so, how to solve it?

I configured the toolbox of RGBT. The previous experiment did not analysis field, which was a bug, but it has been solved now.
