### ISSUE TITLE
Passed in MATLAB tracker but failed in PYTHON tracker

### ISSUE THREAD

**Issue by AstoncPou** [votchallenge/vot-toolkit#205]
Hello, I test this toolkit with tutorial in http://www.votchallenge.net/howto/workspace.html

I successfully integrated tracker written in MATLAB,
tracker_label = 'NCC';
tracker_command = generate_matlab_command('ncc.', {'vot-toolkit-master/tracker/examples/matlab'});
tracker_interpreter = 'matlab';

after that, I tested integrating tracker written in python and failed.

tracker_label = ['ncc'];
tracker_command = generate_python_command('python_ncc.py', {'D:\vot2018\vot-toolkit\tracker\examples\python\'});
tracker_interpreter = 'python';

Error log :

>>run_test
Initializing workspace ...
Verifying native components ...
Testing TraX protocol support for tracker ncc.
Tracker execution interrupted: Unable to start the tracker process
TraX support not detected.
tracker_load (line 127)
Tracker has not passed the TraX support test.
run_test (line 8)
tracker = tracker_load('ncc');

**Comment by AstoncPou** [comment]
NEXT is the new question!!
Initializing workspace ...
Verifying native components ...
Testing TraX protocol support for tracker ncc.
CLIENT: Socket opened successfully on port 9109.
CLIENT: Creating process "C:\Users\Acer\AppData\Local\Programs\Python\Python35\python.exe"  -c "import sys; sys.path.append('D:\vot2018\vot-toolkit\native\trax\python');sys.path.append('D:\vot2018\vot-toolkit\tracker\examples\python'); import python_ncc.py"
CLIENT: Working directory is C:\Users\Acer\AppData\Local\Temp\tp2b1238d8_66ff_4a4c_9e07_04ea88ed520c
CLIENT: Starting process
CLIENT: Unable to start process
CLIENT: Cleaning up.
CLIENT: Stopping logger thread
CLIENT: Stopping watchdog thread
CLIENT: Flushing streams
CLIENT: Process should be terminated.
CLIENT: Stopping logger.
CLIENT: Tracker exited (exit code 1)
CLIENT: Closing server socket.
Tracker execution interrupted: Unable to start the tracker process
TraX support not detected.

**Comment by AstoncPou** [comment]
i just change the connection style to scoket，where is the wrong??

**Comment by AstoncPou** [comment]
i have just test the ncc.py  successful in ubuntu, but in win 10 ,it's always stays in 'testing TraX protocol support for tracker ncc',and it no result! i can't find where is the error!! by debug i find it run to tracker_run.m and in line 76 it run the ‘data = traxclient(tracker.command,callback,....data,mexargs{:} );'it not get data but also catch error.however in ubuntu,it will jump to function callback in tracker_test in line 55,then jump to ~isempty(failure) and ispc() in tracker_run in line 85 and line 91,finally it change 'support' to 1, but in win 10 ,it can't debug. it always stays in 'try data = traxclient(tracker.command, ....);' it does't jump to anywhere.the tracker connection style both is standard,i'm not sure if the difference of OS make it, I also change the connection style to scoket in win10,but it does't work.what's more,in the ubuntu ,the py version is 2.7,but in win10,the python is 3.5

**Comment by AstoncPou** [comment]
@ lukacu

**Comment by AstoncPou** [comment]
@lukacu after change python's version to 2.7 in win10 ,ncc.py still can't run !!what can i do ?

**Comment by tedchen1027** [comment]
I have same problem. Matlab tracker run_test will have error at the end of test, but run_experiment is ok.
Python tracker can't create trax client, I have googled many days, but have no solution. Any configurations need to be changed or other things need to be modified? Thanks for any information.

# Error condition  
    >>run_test
    Initializing workspace ...
    TraX source code already present.
    Verifying native components ...
    Loading sequences ...
    Loading sequence motocross
    Loading sequence sunshade
    Loading sequence surfing
    Testing TraX protocol support for tracker NCC.
    Tracker execution interrupted: Unable to start the tracker process
    TraX support not detected.

# Environment
*Windows 10 -- 1809
*Matlab R2018b update2 -- 9.5.0 
*Anaconda Python 3.6.5 -- I have added python path to PATH

# tracker_NCC.m
    tracker_label = ['NCC'];
    tracker_command = generate_python_command('ncc', {'D:\vot-toolkit-master\tracker\examples\python\python_ncc.py'});
    tracker_interpreter = 'python'

**Comment by AstoncPou** [comment]
CHANGE 
tracker_command = generate_python_command('ncc', {'D:\vot-toolkit-master\tracker\examples\python\python_ncc.py'}); 
TO 
tracker_command = generate_python_command('python_ncc', {'D:\vot-toolkit-master\tracker\examples\python'});

**Comment by AstoncPou** [comment]
@tedchen1027 the first is script,and the second is path

**Comment by tedchen1027** [comment]
@AstoncPou Thx for your reply, but you try it ok now, I have changed it, and it is no use. :(

**Comment by AstoncPou** [comment]
what's error

**Comment by tedchen1027** [comment]
Testing TraX protocol support for tracker NCC.
Tracker execution interrupted: Unable to start the tracker process
TraX support not detected.
Error using tracker_load (line 127)
Tracker has not passed the TraX support test.

Error in run_test (line 8)
tracker = tracker_load('NCC');

**Comment by AstoncPou** [comment]
you can try it  in ubuntu,it'll be work,

**Comment by tedchen1027** [comment]
ok, got it, poor windows ...  anyway thanks

**Comment by wangaixue** [comment]
@AstoncPou hey, this toolkit is ok in ubuntu. i meet the same question with you

**Comment by lukacu** [comment]
From what I can see this has mostly been resolved, closing.
