### ISSUE TITLE
Python tracker， can't initialize with polygon

### ISSUE THREAD

**Issue by TSSSS4** [votchallenge/vot-toolkit#206]
When initialize python tracker's vot handle with "polygon":`handle = vot.VOT("polygon")`, it will get blocked here
https://github.com/votchallenge/vot-toolkit/blob/0b7f5c4de5a2ec795fc141f9e73d8404640fa377/tracker/examples/python/vot.py#L95

and MATLAB get this error:
`
Error using traxclient
Did not receive response.

Error in tracker_run (line 77)
data = traxclient(tracker.command, callback, ...

Error in workspace_test (line 53)
tracker_run(tracker, @callback, data);

Error in run_test (line 10)
workspace_test(tracker, sequences);
`

While it works well with`handle = vot.VOT("rectangle")`, why is this happening?

**Comment by lukacu** [comment]
Not really sure, it should work. We have also updated the python bindings, have you tried it with the new ones?

**Comment by TSSSS4** [comment]
> Not really sure, it should work. We have also updated the python bindings, have you tried it with the new ones?

I've just downloaded the latest version of vot-toolkit and tried again, it still not works, the program got blocked at the same place

**Comment by lukacu** [comment]
I did not express myself correctly, I forgot that the new stuff is not yet in master branch. We will merge it soon, and then you can test it.

**Comment by TSSSS4** [comment]
> I did not express myself correctly, I forgot that the new stuff is not yet in master branch. We will merge it soon, and then you can test it.

Ok thanks
