### ISSUE TITLE
Can't import tensorflow

### ISSUE THREAD

**Issue by zhenxili96** [votchallenge/vot-toolkit#207]
Hi, I managed to test the python_ncc tracker and get the html result of it. But if I add "import tensorflow as tf" in "python_ncc.py" when I run "run_experiments.m", it shows:
`TraX support not detected.
  Error using tracker_load .  
  Tracker has not passed the TraX support test`.

How can I import tensorflow in my code?

**Comment by sunhao12121** [comment]
have u solve the problem?

**Comment by lukacu** [comment]
Well this is not really a lot of information to work with, can you check the log files that are generated? Probably you have to provide some link paths and such as tensorflow is a complex library.

**Comment by lukacu** [comment]
Probably related  to #173

**Comment by lukacu** [comment]
Closing because no additional information was provided.
