### ISSUE TITLE
Unable to establish connection. TraX support not detected.

### ISSUE THREAD

**Issue by xi-mao** [votchallenge/vot-toolkit#209]
Hello! I can run matlab_ncc successfully ,but failed in python_ncc. My environment is matlab2017b,python3.5(I also try python2.7 still fail), gcc5.4(I also try gcc4.9 , didn‘t work)。 Can anyone help me solved the problem？

**Comment by wangaixue** [comment]
@xi-mao your environment is window or ubuntu？

**Comment by lukacu** [comment]
Please provide more information, like log file. Also, these kind of questions are more suitable for the support forum. Closing.
