### ISSUE TITLE
while use vot2018 toolkit(matlab) to evaluate python-based tracker,i get following troubles:

### ISSUE THREAD

**Issue by feixiaoyu2223** [votchallenge/vot-toolkit#210]
error use generate_python_command (line 48)Unable to locate Python interpreter, please set the "python" global variable manually.

Urgent to get solution,thanks!

**Comment by lukacu** [comment]
You have to set the interpreter path, you are most likely using Windows and the python interpreter there is not located in any standard path. You can use `set_global_variable('python', '...')` to set the absolute path to python.exe.
