### ISSUE TITLE
How to get detail accuracy and robustness of every sequences like in VOT toolkit 5.0.2

### ISSUE THREAD

**Issue by TSSSS4** [votchallenge/vot-toolkit#212]
Hi
Report generated by vot toolkit 6 only lists accuracy of every tag(camera motion, illum change, etc.), and report generated by vot toolkit 5 lists accuracy of every sequences, how to get the latter kind of report by using vot toolkit 6?

**Comment by lukacu** [comment]
This is more appropriate for the support forum. In short you have to run the analysis that computes these measures on per-sequence basis.
