### ISSUE TITLE
vot.convert_region returns point tuples instead of Point

### ISSUE THREAD

**Issue by jonathantompson** [votchallenge/vot-toolkit#214]
The points list defined at: https://github.com/votchallenge/vot-toolkit/blob/master/tracker/examples/python/vot.py#L69

thru L72, appends tuples of (x, y). This causes issues throughout the code if you try and then pass the result to VOT for eval. Instead points should be a list of Point instances (https://github.com/votchallenge/vot-toolkit/blob/master/tracker/examples/python/vot.py#L24) as is standard everywhere else.

**Comment by lukacu** [comment]
Thanks, we will fix this.

**Comment by jonathantompson** [comment]
Thanks!

**Comment by lukacu** [comment]
With the change of the Python wrapper (will be merged from branch channels) this is probably no longer an issue, but let us know if there is still something like this in the code.

**Comment by jonathantompson** [comment]
Thanks! Is there a commit associated with the python wrapper change?
