### ISSUE TITLE
Python tracker trax support not detected

### ISSUE THREAD

**Issue by DianJin2018** [votchallenge/vot-toolkit#215]
Hi, I have just downloaded the latest vot-toolkit and pass the matlab version ncc test in vot challenge18, but when I tried the python version ncc test, it failed . Here is my tracker config, typically ncc python script test.

> tracker_label = ['hust_py_siamese_18'];
tracker_command = generate_python_command('python_ncc', {'/home/makalo/workspace/vot2019/vot-toolkit-master/tracker/examples/python/'});
tracker_interpreter = 'python'; 

But when I run the run_test.m, it failed, here is the log

> Traceback (most recent call last):
  File "/home/makalo/workspace/vot2019/vot-toolkit-master/tracker/examples/python/vot.py", line 17, in <module>
    import trax
ModuleNotFoundError: No module named 'trax'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/makalo/workspace/vot2019/vot-toolkit-master/tracker/examples/python/python_ncc.py", line 3, in <module>
    import vot
  File "/home/makalo/workspace/vot2019/vot-toolkit-master/tracker/examples/python/vot.py", line 19, in <module>
    raise Exception('TraX support not found. Please add trax module to Python path.')
Exception: TraX support not found. Please add trax module to Python path.

it seems that python support for trax is not implemented, so I check out in 
`/home/makalo/workspace/vot2019/vot-toolkit-master/native/trax/support/python/`
and tried to install trax in the python module, after this I encounted this error

> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/makalo/workspace/vot2019/vot-toolkit-master/tracker/examples/python/python_static.py", line 3, in <module>
    import vot
  File "/home/makalo/workspace/vot2019/vot-toolkit-master/tracker/examples/python/vot.py", line 16, in <module>
    from trax import *
  File "/home/makalo/anaconda3/lib/python3.6/site-packages/trax/__init__.py", line 2, in <module>
    from .wrapper import PropertiesWrapper
  File "/home/makalo/anaconda3/lib/python3.6/site-packages/trax/wrapper.py", line 4, in <module>
    from .internal import trax_image_release, trax_region_release, trax_cleanup, trax_properties_release
  File "/home/makalo/anaconda3/lib/python3.6/site-packages/trax/internal.py", line 147, in <module>
    trax_no_log = (struct_trax_logging).in_dll(_libraries['trax'], 'trax_no_log')
KeyError: 'trax'

then I check the code internal.py  in line 61 and found that it seems that it can't find libtrax.so file
`_libraries['trax'] = ctypes.CDLL('libtrax.so')`

could you please tell me how to handle this or what should I do to get trax support for python tracker from the beginning, thank you.

**Comment by lukacu** [comment]
Take a look at the `tracker/examples/tracker_Demo_py.m`, it is clearly stated there that you have to add path to the trax C library (if the library is not in the system path). Also, please use our forum for this kind of issues.

**Comment by jimiolaniyan** [comment]
@lukacu How do I find the `<path-to-trax-build-dir>`? Is this documented anywhere?

**Comment by lukacu** [comment]
Maybe build dir is not really the best name, we should fix that. The point is that you should find the location of libtrax.so and use that here. But to get the libtrax.so you will have to compile libtrax manually with CMake or download precompiled bundles from bintray (Matlab cannot compile anything that is not a Mex file). There are instruction on how to compile libtrax in the library documentation.

**Comment by jimiolaniyan** [comment]
@lukacu That worked, but I doing a `run_test` with the `ball2` sequence and it has now taken more than 20 mins and it has not returned any results. Should it take that long for a single sequence? I am using the `ncc` tracker with the python interpreter.

**Comment by zhanglichao** [comment]
Has it been solved ?

**Comment by Ruohan1** [comment]
@jimiolaniyan Excuse me, can you show your tracker_XXX  file?

**Comment by zhanglichao** [comment]
I’ve solved it by referring #224.

Thanks!

**Comment by skyoung** [comment]
I still cannot find the '/bin' folder even after compiling trax in build folder, any hints?

**Comment by ZhouZhang233** [comment]
> I’ve solved it by referring #224.
> 
> Thanks!

I couldn't find libtrax.so . where can find it. Thanks
