### ISSUE TITLE
Workspace create The command 'cl' exited with a return value '-1073741701

### ISSUE THREAD

**Issue by workerbee79** [votchallenge/vot-toolkit#218]
Verifying native components ...
Building with 'Microsoft Visual C++ 2017'.
ERROR: Unable to compile MEX function: "The command 'cl' exited with a return value '-1073741701'".
Error using initialize_native (line 87)
Unable to compile all native resources.

Error in workspace_create (line 143)
initialize_native();

**Comment by lukacu** [comment]
Please do not just copy/paste arbitrary error here, this looks like an error somewhere in your configuration of the build environment. Closing as unrelated. Other issues like this should go to the support forum and not issue tracker.
