### ISSUE TITLE
How can I download the dataset directly instead of using matlab toolkit?

### ISSUE THREAD

**Issue by buptchan** [votchallenge/vot-toolkit#221]
Hi, 
When I download the sequences using matlab toolkit, I alway encounter this issue:
---
Unable to retrieve sequence bundle from the server. This is either a connection problem or the server is temporary offline.
Error using workspace_load (line 150)
---
It might be the problem of my own network. So I wonder whether there is another way to download VOT dataset?

**Comment by lukacu** [comment]
Well, the dataset is split into multiple zip files, connected using a json description file. So you can write a script that will download all the zips and extract them. You can also do it manually, but it will take a long time.
