### ISSUE TITLE
Tracker has not passed the TraX support test: KeyError: 'trax'

### ISSUE THREAD

**Issue by Dawn5786** [votchallenge/vot-toolkit#224]
Ｈello, lucas, I am trying to run the python_ncc.py tracker using the VOT2019 toolkit,

My configuration is: Ubuntu16.04, Matlab2016b, anaconda3/python
I put Trax into the native folder after manually compiling it.

But I have encountered the following problem:

>> run_test
Initializing workspace ...
Verifying native components ...
Testing TraX protocol support for tracker ncc.
CLIENT: Creating process /home/anaconda3/bin/python  -c "import sys; sys.path.append('/home/Documents/VOT19/vot-toolkit-master/workspace_1'); import python_ncc"
CLIENT: Working directory is /tmp/tpc658be8c_cfb9_473e_b6c4_ffffa0c526a6
CLIENT: Starting process
CLIENT: Setting up TraX with standard streams connection
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/Documents/VOT19/vot-toolkit-master/workspace_1/python_ncc.py", line 3, in <module>
    import vot
  File "/home/Documents/VOT19/vot-toolkit-master/workspace_1/vot.py", line 19, in <module>
    import trax
  File "/home/Documents/VOT19/vot-toolkit-master/native/trax/__init__.py", line 2, in <module>
    from .wrapper import PropertiesWrapper
  File "/home/Documents/VOT19/vot-toolkit-master/native/trax/wrapper.py", line 4, in <module>
    from .internal import trax_image_release, trax_region_release, trax_cleanup, trax_properties_release
  File "/home/Documents/VOT19/vot-toolkit-master/native/trax/internal.py", line 147, in <module>
    trax_no_log = (struct_trax_logging).in_dll(_libraries['trax'], 'trax_no_log')
KeyError: 'trax'
CLIENT: Flushing streams
CLIENT: Process should be terminated.
CLIENT: Unable to establish connection.
CLIENT: Stopping logger.
CLIENT: Tracker exited (exit code 1)
CLIENT: Cleaning up.
CLIENT: Stopping logger thread
CLIENT: Trying to stop process using protocol.
Tracker execution interrupted: Unable to establish connection.
TraX support not detected.
Error using tracker_load (line 127)
Tracker has not passed the TraX support test.

Error in run_test (line 8)
tracker = tracker_load('ncc');

**Comment by lukacu** [comment]
See #215.
