### ISSUE TITLE
TraX support not detected whenever in windows or ubuntu

### ISSUE THREAD

**Issue by feixiaoyu2223** [votchallenge/vot-toolkit#227]
Urgently asking for help!
when on ubuntu16.04, i use matlabr2017b, whether the interpreter is python or matlab, it always prints the following error.However, when on windows,i use matlabr2016a, just error on python interpreter.Errors are as follows:
Tracker execution interrupted: Invalid MEX-file '/home/fly/Documents/vot-toolkit2018/native/traxclient.mexa64': 
Missing symbol '_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc' required by '/home/fly/Documents/vot-toolkit2018/native/traxclient.mexa64'
Missing symbol '_ZNSt13runtime_errorC1EPKc' required by '/home/fly/Documents/vot-toolkit2018/native/traxclient.mexa64'
Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_replaceEmmPKcm' required by '/home/fly/Documents/vot-toolkit2018/native/traxclient.mexa64'
Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4swapERS4_' required by '/home/fly/Documents/vot-toolkit2018/native/traxclient.mexa64'
Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_appendEPKcm' required by '/home/fly/Documents/vot-toolkit2018/native/traxclient.mexa64'
Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_assignERKS4_' required by '/home/fly/Documents/vot-toolkit2018/native/traxclient.mexa64'
Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm' required by '/home/fly/Documents/vot-toolkit2018/native/traxclient.mexa64'
Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_mutateEmmPKcm' required by '/home/fly/Documents/vot-toolkit2018/native/traxclient.mexa64'
Missing symbol '_ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEED1Ev' required by '/home/fly/Documents/vot-toolkit2018/native/traxclient.mexa64'
Missing symbol '_ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE' required by '/home/fly/Documents/vot-toolkit2018/native/traxclient.mexa64'
Missing symbol '_ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE' required by '/home/fly/Documents/vot-toolkit2018/native/traxclient.mexa64'
Missing symbol '_ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE' required by '/home/fly/Documents/vot-toolkit2018/native/traxclient.mexa64'.
TraX support not detected.

Besides,it warns:
Warning: You are using gcc version '5.4.0'. The version of gcc is not supported. The version currently supported with MEX is '4.9.x'. Thanks for your answers!

**Comment by lukacu** [comment]
This looks like a very common issue with Matlab stdlib linking, the problem is that Matlab brings its own stdlibs which are not compatible with system ones ... try googling a bit, there are plenty of posts on this issue. It is not a problem that we can solve for the toolkit.

**Comment by feixiaoyu2223** [comment]
ok,thanks for your reply anyway.


------------------




 




------------------ 原始邮件 ------------------
发件人: "Luka Čehovin Zajc"<notifications@github.com>;
发送时间: 2019年5月10日(星期五) 晚上6:13
收件人: "votchallenge/vot-toolkit"<vot-toolkit@noreply.github.com>;
抄送: "Fred.Fly"<441275397@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [votchallenge/vot-toolkit] TraX support not detected whenever inwindows or ubuntu (#227)




This looks like a very common issue with Matlab stdlib linking, the problem is that Matlab brings its own stdlibs which are not compatible with system ones ... try googling a bit, there are plenty of posts on this issue. It is not a problem that we can solve for the toolkit.

**Comment by GithubMaker666** [comment]
I have the same problem, when I change the matlab version--2017b to 2018a,the problem have been solved
