### ISSUE TITLE
configuration.m is missing?

### ISSUE THREAD

**Issue by SampsonKwan** [votchallenge/vot-toolkit#229]
In the 

> Prerequisites

  at [http://www.votchallenge.net/howto/integration_channels.html](http://www.votchallenge.net/howto/integration_channels.html) , it says 

> In the configuration.m set the following command:

But I found that the  configuration.m is missing and is in .gitignore, why?

**Comment by lukacu** [comment]
You have to create a workspace first, configuration.m is autogenerated when that happens. Please read the guide on[ creating a workspace](http://www.votchallenge.net/howto/workspace.html).
