### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by wyukai** [votchallenge/vot-toolkit#231]
CLIENT: Tracker process ID: 30074
CLIENT: Connection with tracker established.
@@TRAX:initialize "file:///home/wangkai/vot-toolkit-dev/rafl-workspace/sequences/ants1/color/00000034.jpg" "399.4200,842.7900,68.5500,58.0300" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/wangkai/vot-toolkit-dev/vot2018/RAFL/vot_RAFL.py", line 24, in <module>
    handle = vot.VOT("rectangle")
  File "/home/wangkai/vot-toolkit-dev/vot2018/RAFL/vot.py", line 96, in __init__
    assert(request.type == 'initialize')
AssertionError
CLIENT: Timeout reached. Stopping tracker process ...

My traker can pass run_test ,but when I run run_experiments ,I got this issue.

**Comment by lukacu** [comment]
Yes, the problem is (very likely) that you are doing some long computation on the first frame, it is clearly written that there is a timeout. Search the forum on how to increase the timeout value.
