### ISSUE TITLE
Toolkit version 7 IO error

### ISSUE THREAD

**Issue by NaveenPaluru** [votchallenge/vot-toolkit#239]
I am planning to participate in VOT challenge this year. In this regard I have successfully integrated my tracker with VOT Toolkit (version 6) and got the required results and reports. However,  when I  am  trying   to use  recent version of the toolkit (i.e. version 7) I am getting the following error and I could not figure out how to rectify the same.

1.1.0

calling again

Traceback (most recent call last):

File "<string>", line 1, in <module>

File "/media/root1/hd2/NAV/My_Research_IIT_Tirupati/VOT_Submissions/Tracking/vot_tracker.py", line 79, in <module>

handle = vot.VOT("polygon")

File "/media/root1/hd2/NAV/My_Research_IIT_Tirupati/VOT_Submissions/Tracking/vot.py", line 104, in __init__

self._files = [x.strip('\n') for x in open('images.txt', 'r').readlines()]

IOError: [Errno 2] No such file or directory: 'images.txt'

**Comment by lukacu** [comment]
It looks like you are using a very old vot.py wrapper that does not use TraX protocol and tries to read some files that are not provided anymore by the toolkit because everything is passed over the protocol. Please use the newest vot.py

**Comment by NaveenPaluru** [comment]
Thank you that solved my issue.


Naveen
MS by Research
IIT Tirupati
