### ISSUE TITLE
Question regarding robustness metric

### ISSUE THREAD

**Issue by rgoroshin** [votchallenge/vot-toolkit#244]
Hi, 

Apologies for the duplicate question I left on Google Groups some time ago. 

A question regarding robustness: 

Robustness is in the range [0, 1] in the plots but much larger than 1.0 in the table, where does the discrepancy come from and how can the robustness number score in [0, 1] (reported by most papers) be obtained via the VOT toolkit?

thanks!

**Comment by deeplearnerJHB** [comment]
Hello. Have you solved this problem? I'm also very confused about such case!

**Comment by alanlukezic** [comment]
Hi, for more details bout the robustness please see the discussion here: https://groups.google.com/forum/?hl=en#!topic/votchallenge-help/xCaIu2ybLm8
