### ISSUE TITLE
Matlab2019a crashed when testing Trax protocol support for tracker ncc

### ISSUE THREAD

**Issue by wsuny** [votchallenge/vot-toolkit#245]
Platform: ubuntu18.04
MATLAB: R2019a
Tracker: ncc
Interpreter: MATLAB

**Comment by YuzheSHI** [comment]
I am suffering from the same problem... You are NOT alone.

**Comment by YuzheSHI** [comment]
![1569731207983](https://user-images.githubusercontent.com/46876726/65840881-951b6480-e350-11e9-9f10-32cdb58a333a.png)
![1569732106367](https://user-images.githubusercontent.com/46876726/65840882-951b6480-e350-11e9-9b2f-305bee09269d.png)
After downloading the sequences, matlab may get crashed when checking TraX protocol environment and I have to rerun matlab.

**Comment by YuzheSHI** [comment]
And this is the crash report. Something seems wrong with mex.


--------------------------------------------------------------------------------
             Assertion detected at 一 9月 30 07:19:58 2019 +0800
--------------------------------------------------------------------------------

Configuration:
  Crash Decoding           : Disabled - No sandbox or build area path
  Crash Mode               : continue (default)
  Default Encoding         : UTF-8
  Deployed                 : false
  Desktop Environment      : ubuntu:GNOME
  GNU C Library            : 2.27 stable
  Graphics Driver          : Unknown software 
  Graphics card 1          : 0x10de ( 0x10de ) 0x1d12 Version 390.116.0.0 (0-0-0)
  Graphics card 2          : 0x8086 ( 0x8086 ) 0x5917 Version 0.0.0.0 (0-0-0)
  Java Version             : Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  MATLAB Architecture      : glnxa64
  MATLAB Entitlement ID    : 4205217
  MATLAB Root              : /usr/local/MATLAB/R2019b
  MATLAB Version           : 9.7.0.1190202 (R2019b)
  OpenGL                   : software
  Operating System         : Ubuntu 18.04.2 LTS
  Process ID               : 3589
  Processor ID             : x86 Family 6 Model 142 Stepping 10, GenuineIntel
  Session Key              : 27d4fef8-5630-4e72-b41e-89c97aaaf5b2
  Static TLS mitigation    : Enabled: Full
  Window System            : The X.Org Foundation (12001000), display :0

Fault Count: 1


Assertion in find at management.cpp line 712:
find: no active context for type 'std::shared_ptr<InterruptStateData>'

Register State (captured):
  RAX = 0000000000000000  RBX = 00007f13826d7d08
  RCX = 000000000000000a  RDX = 00007f13826c8e00
  RSP = 00007f11f5ce3f80  RBP = 00007f11f5ce4340
  RSI = 00007f13826902e6  RDI = 00007f11f5ce3f90

   R8 = 00007f11f5ce4255   R9 = 00007f11f5ce4255
  R10 = 00007f138357ba7e  R11 = 0000001000000006
  R12 = 00007f13826e7d98  R13 = 00007f11f5ce4be0
  R14 = 00007f13858e3e8c  R15 = 00007f13858e4deb

  RIP = 00007f13825e00be  EFL = 733a3a6474732720

   CS = 6168   FS = 6572   GS = 5f64

Stack Trace (captured):
[  0] 0x00007f13825d7623    /usr/local/MATLAB/R2019b/bin/glnxa64/libmwfl.so+00828963
[  1] 0x00007f13825d781c    /usr/local/MATLAB/R2019b/bin/glnxa64/libmwfl.so+00829468 _ZN10foundation4core4diag15stacktrace_base7captureEm+00000028
[  2] 0x00007f13825dc44f    /usr/local/MATLAB/R2019b/bin/glnxa64/libmwfl.so+00848975
[  3] 0x00007f13825dc5b0    /usr/local/MATLAB/R2019b/bin/glnxa64/libmwfl.so+00849328
[  4] 0x00007f13858d375e /usr/local/MATLAB/R2019b/bin/glnxa64/libmwfoundation_usm.so+00075614
[  5] 0x00007f13858e0898 /usr/local/MATLAB/R2019b/bin/glnxa64/libmwfoundation_usm.so+00129176 _ZN10foundation3usm6DetailINS0_5scope3MvmEE4findEmRKSt9type_info+00000136
[  6] 0x00007f138276a04e      /usr/local/MATLAB/R2019b/bin/glnxa64/libut.so+00528462
[  7] 0x00007f1382769429      /usr/local/MATLAB/R2019b/bin/glnxa64/libut.so+00525353 _ZN16utInterruptState18IsInterruptPendingEv+00000009
[  8] 0x00007f11ee5e7d39             /home/shi/vot/native/traxclient.mexa64+00023865
[  9] 0x00007f11ee5f1784             /home/shi/vot/native/traxclient.mexa64+00063364
[ 10] 0x00007f1384a606db              /lib/x86_64-linux-gnu/libpthread.so.0+00030427
[ 11] 0x00007f13841f188f                    /lib/x86_64-linux-gnu/libc.so.6+01185935 clone+00000063
[ 12] 0x0000000000000000                                   <unknown-module>+00000000

**Comment by lukacu** [comment]
There are unfortunately issues with new Matlab versions for reasons that are very technical. Since we are planning to move to Python for the next challenge we will not even attempt to fix this (it is likely that a fix is even impossible because Matlab is closed source). The currently recommended bypass is to use Matlab lower than 2018a.
