### ISSUE TITLE
matlab2019b ERROR: Unable to compile MEX function: "MEX 找不到使用 -l 选项指定的库 'ut'。

### ISSUE THREAD

**Issue by x670783915** [votchallenge/vot-toolkit#246]
Verifying native components ...
ERROR: Unable to compile MEX function: "MEX 找不到使用 -l 选项指定的库 'ut'。
 MEX 已搜索具有以下名称之一的文件: 
 libut.a
ut.lib
libut.lib 
 请验证库名称是否正确。如果该库不在
现有路径上，请使用 -L 选项指定路径。
".
错误使用 initialize_native (line 87)
Unable to compile all native resources.

出错 workspace_create (line 143)
initialize_native();
 
after i installed mingw-win64, i got this by run run_test.m 
how can i fix it ?

**Comment by lukacu** [comment]
I am not sure how to get it working with mingw, we are usually using Visual Studio on Windows. But there were a couple of discussions regarding the ut library in old issues and on the forum, please search these topics first.
