### ISSUE TITLE
How to read the visible and ir data in the VOT_RGBT2019 running script?

### ISSUE THREAD

**Issue by xjtuwh** [votchallenge/vot-toolkit#247]
I want to know how to test a  code on VOT_RGBT2019. How to read the visible and ir data in the VOT_RGBT2019 running script?

**Comment by lukacu** [comment]
Which language are you using? Every wrapper does this a bit differently, but for example in Python you can check out the example for the RGBD challenge, it is the same for RGBT, just replace the rgbd with rgbt at line 12 and then you will get IR images instead of depth when running on the correct dataset. Please use our forum for further questions regarding this.

**Comment by xjtuwh** [comment]
Thank you very much for your fast replay. I got it~ @lukacu

**Comment by xjtuwh** [comment]
But where is your forum?

**Comment by lukacu** [comment]
[Here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/votchallenge-help).

**Comment by xjtuwh** [comment]
Ok, thank you very much~

**Comment by najingligong1111** [comment]
> Which language are you using? Every wrapper does this a bit differently, but for example in Python you can check out the example for the RGBD challenge, it is the same for RGBT, just replace the rgbd with rgbt at line 12 and then you will get IR images instead of depth when running on the correct dataset. Please use our forum for further questions regarding this.
 
when using rgbt   dataset,  it produces the following error:
>> run_test
Initializing workspace ...
Checking for toolkit updates on GitHub.
Verifying native components ...
Loading sequences ...
Undefined function or variable 'mask'.

Error in sequence_create (line 47)
    channels.(default_channel) = fullfile(directory, mask);

Error in sequence_load (line 154)
    sequences{end+1} = sequence_create(sequence_path); %#ok<AGROW>

Error in workspace_load (line 146)
    sequences = sequence_load(sequences_directory, ...

Error in run_test (line 6)
[sequences, experiments] = workspace_load();

The folder is like this:
vot_toolkit/sequences/xx/ir    vot_toolkit/sequences/xx/color    xx is the class.

**Comment by eefnn** [comment]
> I want to know how to test a code on VOT_RGBT2019. How to read the visible and ir data in the VOT_RGBT2019 running script?

你好，请问你的这个问题怎么解决的，可以交流一下吗，谢谢
