### ISSUE TITLE
available integrated stacks of new toolkit

### ISSUE THREAD

**Issue by lawpdas** [votchallenge/vot-toolkit#254]
```
List of available integrated stacks: 
 * vot2013 - VOT2013 challenge
 * testing - VOT testing
 * vot2017 - VOT2017 challenge
 * vot2015 - VOT2015 challenge
 * vot2014 - VOT2014 challenge
 * vottir2016 - VOT-TIR2016 challenge
 * vottir2015 - VOT-TIR2015 challenge
 * vot2019 - VOT-ST2019 challenge
 * vot2016 - VOT2016 challenge
 * vot2018 - VOT-ST2018 challenge
```
There are no long-term challenge and RGBD challenge. Do we need to use  matlab toolkit for these challenges?

**Comment by lukacu** [comment]
This bug is related to the beta version of the Python toolkit, this is not the right repository. Also, as mentioned in the announcement, the Python toolkit is not yet complete and you should not use it to perform real evaluation. Also, some stuff is missing.
