### ISSUE TITLE
error_pos('Outer level structure must be an object or an array')

### ISSUE THREAD

**Issue by iminfine** [votchallenge/vot-toolkit#257]
When I run the script run_experiments.m after creating workspace I got this error:

Verifying native components ...
Loading sequences ...
Error using json_decode/error_pos (line 196)
Outer level structure must be an object or an array : ... F<error> ...

Error in json_decode (line 29)
            error_pos('Outer level structure must be an object or an array');

Error in sequence_load (line 56)
        meta = json_decode(fileread(listing));

Error in workspace_load (line 146)
    sequences = sequence_load(sequences_directory, ...

Error in run_experiments (line 6)
[sequences, experiments] = workspace_load();

How to fix it?

**Comment by lukacu** [comment]
Please specify the stack that you are using and matlab version. It looks to me like an error with downloading the json file manifest that contains links to individual sequences.

**Comment by XDUSPONGE** [comment]
> When I run the script run_experiments.m after creating workspace I got this error:
> 
> Verifying native components ...
> Loading sequences ...
> Error using json_decode/error_pos (line 196)
> Outer level structure must be an object or an array : ... F ...
> 
> Error in json_decode (line 29)
> error_pos('Outer level structure must be an object or an array');
> 
> Error in sequence_load (line 56)
> meta = json_decode(fileread(listing));
> 
> Error in workspace_load (line 146)
> sequences = sequence_load(sequences_directory, ...
> 
> Error in run_experiments (line 6)
> [sequences, experiments] = workspace_load();
> 
> How to fix it?

hello I have meet the same probelm 
so how do you solve it

**Comment by iminfine** [comment]
Download the dataset manually, and put the unzip files into the sequences folder under the workspace.

**Comment by wxs1997** [comment]
> Download the dataset manually, and put the unzip files into the sequences folder under the workspace.

vot-toolkit/workspace/sequences/vot2016/blabla...
or
vot-toolkit/workspace/sequences/blabla...
?

**Comment by mbhdzz** [comment]
Hello，is this problem solved? I need your help please!
