### ISSUE TITLE
possible bug - missing argument in call of function "normalize_speed" in the file "calculate_scores"

### ISSUE THREAD

**Issue by vojirt** [votchallenge/vot-toolkit#42]
line 44 of file calculate_scores.m

function normalize_speed() takes 5 arguments but the caller passes only 4, skipping one in the middle (3rd), resulting in wrong arguments order.

instead of tracker structure, the function get sequence structure resulting in the error in "performance" field test
if ~isfield(tracker, 'performance')
    error('Tracker %s has no performance profile, unable to normalize speed.', tracker.identifier);
end;

**Comment by vojirt** [comment]
possible related to #38

**Comment by lukacu** [comment]
I think that this has been resolved, the calculate_scores function no longer exist and will be replaced by a report that generates per-tracker performance summary.
