### ISSUE TITLE
possible bug - NaN values in region.txt after tracker failure

### ISSUE THREAD

**Issue by vojirt** [votchallenge/vot-toolkit#43]
Probably missing check if the gt is valid when creating the region.txt file for sub-sequence after tracker failure (for gt with multiple consecutive NaN entries).

Is the tracker failure because of gt is NaN count as a failure in the evaluation ?

**Comment by lukacu** [comment]
Why would you have NaNs in the groundtruth? I agree that we could add a test, but I am just wondering how to interpret these frames then? So far we did not have a scenario like this, so there was no need for a check.

**Comment by vojirt** [comment]
I know that we are trying to work with the sequences where the object is visible the whole time, however during some sequences with occlusion, there is thin line between occlusion and disappearance (e.g. bicycle sequence frame 174 where the occlusion is almost full). In these cases if the tracker fails before the occlusion and then is re-initialized on the frame with almost full occlusion, it will fail immediately again. 

NaN values in the groundtruth can have therefore 2 purposes: 1) mark when the object is visible (lets say less than 90% of occlusion) 2) therefore mark frames where the tracker can be reinitialized.

This will allow us to include a sequences with short-term object disappearance, if we want to.
If tracker fails on NaN value, it will not be penalized and will be reinitialized on the first valid frame and the NaN entries will not be taken into the account during score computation.

Not sure if this all is worth the effort. I found this during clustering of the new sequences (which contains the NaN values) and want to let you know.

**Comment by lukacu** [comment]
Yes, I agree with you that we need to specify disappearance of objects, but we will perhaps not do this using NaN, but rather using some specific codes, like for failures and initializations. But we can also add a rule to convert NaNs to this code.

**Comment by lukacu** [comment]
This issue was partially addressed in lukacu/trax@34dbf81391973aeab7e8f594cf3e245b1cfb97d7 , all annotations that contain NaN values are now converted to special frames (only a single value), so all you have to do is to filter these frames.

**Comment by lukacu** [comment]
@vojirt can you check if current reading of trajectories is more suited for NaN frames so that I can close the issue? Every frame that contains at least one NaN is now converted to special frame with value 0.

**Comment by vojirt** [comment]
@lukacu I think this solution is ok, what about the support for trackers without the TraX protocol? The toolkit should give the same bbox format in case of TraX or without.

**Comment by lukacu** [comment]
Hm, so you think of initialization of trackers? I do not think this is handled anywhere at the moment, not even for TraX as we assume that the region is available for all frames. Support for skipping frames without annotations should be added, but I will do this later.

**Comment by vojirt** [comment]
yea, it is not a priority now, but I was targeting the issue were trackers can be reinitialized on the frames with major occlusion and such. We can discussed this later.

**Comment by lukacu** [comment]
Should we address this for VOT2016 or postpone it to some later deadline?

**Comment by vojirt** [comment]
I mean this is not a high priority task, but in some rare cases it can create bias for some trackers that will be unlucky enough. But I am not sure how to address this now, so I would leave it open for now and we can discuss the whole issue "on which frames the tracker can be reinitialized?" later.

**Comment by lukacu** [comment]
Due to time constraints I am postponing this until some later milestone.

**Comment by lukacu** [comment]
This is a fairly old issue, so I am closing it. The "object is not visible" issue is addressed in the long-term evaluation where no re-initialization is made. In theory we could also support same sequences in supervised experiments, but at the moment I do not see any practical reason to do this. Somebody can pick it up if it is deemed useful.
