### ISSUE TITLE
Integrate IR vot into the vot-toolkit

### ISSUE THREAD

**Issue by GustavHager** [votchallenge/vot-toolkit#45]
IR vot sub challenge integration, needs an experiment file, and some extension to read .png files

**Comment by lukacu** [comment]
I have now merged the trajectory reading part of the merge request with d9f5f75daa15ca972edd6d9941fe10875158cc43 , so I am closing the issue. I have removed the experiment stack from the commit so that we will introduce those files to the repository when the challenge is opened.
