### ISSUE TITLE
tracker_create.m is missing

### ISSUE THREAD

**Issue by gnebehay** [votchallenge/vot-toolkit#51]
I encounter the following error while running workspace_create. Indeed, the function tracker_create is not contained in the dev branch.

Select one of the available experiment stacks:
 1 - test
 2 - vot2013
 3 - vot2013_extra
 4 - vot2014
Selection: 1
Input an unique identifier for your tracker: DSST
Undefined function 'tracker_create' for input arguments of type 'char'.

Error in workspace_create (line 110)
    tracker_create('identifier', tracker_identifier, 'directory', directory);

**Comment by lukacu** [comment]
Fixing in b7c66e3ad55e3d91df523ca79576f8527d565372
