### ISSUE TITLE
'workspace_create' according to howto

### ISSUE THREAD

**Issue by myro** [votchallenge/vot-toolkit#54]
Currently, http://votchallenge.net/howto/workspace.html
states that you have to add at least 
```
addpath('<vot-toolkit-dir>/workspace'); 
```
to your environment to use 'workspace_create'. If I do that I get notified about missing functions/m-files. ('is_octave.m' is for example not on the path then).

However, 
```
addpath(genpath('<vot-toolkit-dir>'));
```
 works for 'workspace_create'.
This is a minor issue, but maybe the howto could be updated.

**Comment by lukacu** [comment]
Thanks for reporting this, I have updated the instructions and made some changes to the code, please reopen if it is still confusing.
