### ISSUE TITLE
bug in vot.h for native tracker

### ISSUE THREAD

**Issue by barami98** [votchallenge/vot-toolkit#55]
in line 362 to 367

	    for (int j = 0; j < _region->count; j++) {
		    top = MIN(top, _region->y[i]);
		    bottom = MAX(bottom, _region->y[i]);
		    left = MIN(left, _region->x[i]);
		    right = MAX(right, _region->x[i]);
	    }

there is no i. It should be j or change for loop.

I get the error of getline function which works only for linux gcc.
I use Visual Studio 2012 on Win7.

**Comment by gnebehay** [comment]
I just fixed this. Could you check if it works for you?

**Comment by barami98** [comment]
I mentioned two bugs.
Index problem was solved but getline function still doesn't work for me.
Does vot-toolkit focus on linux platform only?

**Comment by gnebehay** [comment]
The VOT Toolkit officially supports Windows, Linux and Mac OS. Thanks for reporting this additional error to us, we will take care of it as soon as possible, but unfortunately not before the beginning of next week.

**Comment by gnebehay** [comment]
I do think however, that you could get around the issue by temporary changing the function call of getline in the relevant position in vot.h to std::getline ( http://www.cplusplus.com/reference/string/string/getline/ ), as you mentioned.

**Comment by lukacu** [comment]
I have added a custom getline implementation and tested compilation in Visual Studio 2010. Can you check if the updated version works for you?

**Comment by lukacu** [comment]
I have also created a short tutorial on establishing a VS project [here](http://votchallenge.net/howto/visualstudio.html). Please make sure that you have the most recent toolkit. I am closing the bug, please reopen it if you still have the same problems.
