### ISSUE TITLE
Report legend column width

### ISSUE THREAD

**Issue by GustavHager** [votchallenge/vot-toolkit#62]
Currently when generating the legend for the report, if the name of a tracker is to long it will overlap with the symbol/name of some tracker in the next column.

This could be fixed by either making the columns wider (is this even possible?) or making the figure larger before generating the pdf/png output image. (this is very easy and what i have done so far)

I suppose it is also possible to truncate the name of the tracker, if it is known how wide a column is. The width varies with the size of the figure window though.

**Comment by lukacu** [comment]
This will not be fixed in Matlab toolkit, closing.
