### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by lukacu** [votchallenge/vot-toolkit#72]
Support trackers written in Python. Related to votchallenge/trax#5.

**Comment by lukacu** [comment]
Python TraX server implementation added to TraX library, instructions and examples have to be added to the toolkit.

**Comment by lukacu** [comment]
Everything done, closing issue.

**Comment by skyoung** [comment]
Does it support python3?

**Comment by lukacu** [comment]
I am not really sure, I have never tested it myself. If it does not, contributions are very welcome, there is probably not that many things to fix (the only questions is if there are some changes that are not compatible with python 2).
