### ISSUE TITLE
Need for help on a running error

### ISSUE THREAD

**Issue by SgrE** [votchallenge/vot-toolkit#76]
hi~
when I follow the support to integrate my tracker into the VOT toolkit, I firstly integrate the NCC tracker just for a test.
When running on this step:"Integrating tracker into the VOT toolkit - Testing integration", running errors on matlab are shown as follows,

%-----------------------------------------------------------------------------------------------------------%
Error using system_wrapper>run_once (line 220)
No result produced by tracker. Stopping.

Error in system_wrapper (line 31)
    [Tr, Tm] = run_once(context.directory, tracker, sequence, start, context);

Error in workspace_test (line 75)
            [trajectory, time] = tracker.run(tracker, sequences{current_sequence},
            struct('repetition', 1, 'repetitions', 1));

Error in run_test (line 10)
workspace_test(tracker, sequences);
%-----------------------------------------------------------------------------------------------------------%

Could you tell me how to solve this bug please?

**Comment by lukacu** [comment]
This is not a bug and does not belong on Github, we have [a support forum](https://groups.google.com/forum/?hl=en#!forum/votchallenge-help) for such cases. Please re-post the problem there and provide more information line your tracker description file, operating system and Matlab version.
