### ISSUE TITLE
Octave does not support nanmean yet

### ISSUE THREAD

**Issue by zhengwy888** [votchallenge/vot-toolkit#77]
nanmean is used in a couple places, but Octave doesn't support it yet. 
can we replace it with something else?

http://wiki.octave.org/Financial_package

**Comment by lukacu** [comment]
Hm, I did not encounter this problem before (I am using Octave 4.0.0 and it has nanmean), but Octave is frequently packed without some functions, so I guess the problem may be real in some cases. I am not sure about the solution, there may be other problematic functions and replacing them all may not really be feasible. Can you provide more informations about the version that you are using?

**Comment by zhengwy888** [comment]
I am using octave from ubuntu 14.04 depo

GNU Octave, version 4.0.0
Copyright (C) 2015 John W. Eaton and others.

with financial package version 0.5.0

For now I have just replace nanmean with the regular mean() and it seems to work just fine.

**Comment by lukacu** [comment]
Well, in some cases it does, but we mainly use nanmean where there is a chance that NaN values may occur in a valid scenario and should be ignored. So replacing nanmean with mean can result in entire result being NaN, which is not correct.

**Comment by aseuteurideu** [comment]
I use statistics package instead of financial package. Seems working.
[https://octave.sourceforge.io/statistics/function/nanmean.html](https://octave.sourceforge.io/statistics/function/nanmean.html)

**Comment by LDBauswlmq** [comment]
> I use statistics package instead of financial package. Seems working.
> https://octave.sourceforge.io/statistics/function/nanmean.html

Lifesaver, thank you!

**Comment by foolwood** [comment]
```
sudo apt-get install octave-statistics             # for nanmean 
sudo apt-get install octave-image                  # for imdilate
```
