### ISSUE TITLE
Possible bug - Error in text when executing run_analysis

### ISSUE THREAD

**Issue by vincenzosantopietro** [votchallenge/vot-toolkit#81]
As stated in the title, I get an error when I try to execute the run_analysis script (that i hadn't with the previous toolkit version).

The output here: 
```
Generating competition report
Error using text
Invalid parameter/value pair arguments

Error in generate_trackers_legend (line 101)
        text(X(t) + 0.2, Y(t), trackers{t}.label, args{:});

Error in report_challenge (line 72)
    lh = generate_trackers_legend(trackers, 'visible', false, 'columns', columns, 'rows', rows);

Error in run_analysis (line 16)
report_challenge(context, experiments, trackers, sequences); % Use this report for official challenge report
 
```

**Comment by RangerKD** [comment]
The same error occurs when I try to execute the run_analysis script. Have you ever solved the problem?

**Comment by vincenzosantopietro** [comment]
@RangerKD At the moment no. @lukacu suggested me to set a breakpoint and check the variables values... please report your values here, it may help developers to understand where the bug is.

**Comment by lukacu** [comment]
Hey, has there been any progress on this? Can somebody provide some usable data that will help me reproduce and fix the bug?

**Comment by vincenzosantopietro** [comment]
@lukacu 
Hi Luka,
I’ve noticed that I didn’t set the tracker label properly. Fixing that value, everithing works now.

**Comment by lukacu** [comment]
Ok, great. I am adding some additional code so that label should be set automatically based on identifier because it was meant to be only a human-readable alternative of the identifier.
