### ISSUE TITLE
Error using octave 4.0+

### ISSUE THREAD

**Issue by micahrichert** [votchallenge/vot-toolkit#84]
Using Octave 4.0.2 on Linux and according to the post (https://github.com/votchallenge/vot-toolkit/issues/70) version 4.0.0 generates the following error:

error: 'nargin' undefined near line 36 column 7
error: called from
unimplemented at line 36 column 3
create_sequence at line 51 column 17
load_sequences at line 67 column 21
workspace_load at line 117 column 15
run_test.m at line 6 column 24

This is most likely caused by a bug in Octave 4 as suggested by this thread: http://savannah.gnu.org/bugs/?45908

Tracing the problem back it seems to be caused by something in the precompiled read_trajectory.mex*.  There is a small memory leak in the code but aside from that there are no obvious issues in read_trajectory.cpp.

The fix seems to be to manually recompile read_sequence a single time after the problem is encountered.  To do so, run the following from the vot-toolkit root directory:
compile_mex('read_trajectory', {[pwd '/sequence/read_trajectory.cpp'], [pwd '/native/trax/lib/region.c']}, {[pwd '/native/trax/lib']}, 'native')

**Comment by lukacu** [comment]
Thanks for the report, I will look into it. Can you be more specific about the memory leak?

**Comment by micahrichert** [comment]
line_buffer is malloced but never freed.

**Comment by lukacu** [comment]
Thank you, it will be fixed.

**Comment by lukacu** [comment]
The issue with pre-compiled binaries in Octave 4 is that they have been compiled for Octave 3.8 and are therefore not compatible with Octave 4, I will have to update our compilation environment but until then it is best to manually compile them. As for the memory leak I still cannot see it, the line_buffer, allocated at line 42 is freed at line 69. Or am I missing something?

**Comment by micahrichert** [comment]
Thank you for looking into the issue.  As far as the memory leak, it looks like that last commit to the file fixed the issue.

**Comment by lukacu** [comment]
Great to hear it. I will try to update our build servers soon as Octave 4 is used significantly more than two years ago.
