### ISSUE TITLE
Speed estimate for deterministic trackers in submission report

### ISSUE THREAD

**Issue by snototter** [votchallenge/vot-toolkit#87]
The evaluation of deterministic trackers stops after 3 repetitions and the per frame times for the remaining repetitions are set to 0 (in `<sequence-name>_times.txt`).
The speed estimate within `report/report_submission.m` (line 135, function `estimate_speed`) does not ignore the skipped repetitions:

> times = csvread(times_file);
> speed = 1 / nanmean(times(:), 1); 

which leads to pretty impressive runtimes for deterministic trackers.
Solution would be to ignore the zeroes, e.g. as

> times = csvread(times_file);
> times(times < eps) = nan;
> speed = 1 / nanmean(times(:), 1); 

or

> times = csvread(times_file);
> speed = 1 / nanmean(times(times > 0), 1); 

Observed this issue with MATLAB R2015a on Ubuntu 14.04, 64bit - latest VOT toolkit 4cfb701a

MWE to demonstrate this issue (Deterministic tracker at 20 fps (i.e. .05 sec/frame), sequence with 100 frames, 15 repetitions):

> times = [repmat(.05, 100, 3), zeros(100, 12)];
> speed_wrong = 1/nanmean(times(:))
> speed_correct = 1/nanmean(times(times > 0))

**Comment by lukacu** [comment]
Great, thanks for a very detailed report. We will have to check when did this error appear in the toolkit, but I expect to investigate it in the following weeks when we process VOT2016 results.

**Comment by lukacu** [comment]
This issue is probably no longer relevant since we have recently removed report_submission function.
