### ISSUE TITLE
error with region to rectangle conversion in vot.py in tracker/example/python 

### ISSUE THREAD

**Issue by bretminnehan** [votchallenge/vot-toolkit#89]
The code right now has a few bugs. Firstly, point.y is used instead of point.x for the left and right bound search. Secondly, the top and left variable are set to sys.float_info.min when they should be set to sys.float_info.max. And conversely for bottom and right.

**Comment by lukacu** [comment]
Thanks for reporting the bug, you are also welcome to submit a pull request :) Otherwise I will look at it in a few days.

**Comment by lukacu** [comment]
OK, fixed. The code is for legacy protocol support so I guess nobody even tested it. Still, it is better to have it working, thanks.
