### ISSUE TITLE
Changed method signature (output) not reflected in the dependent code

### ISSUE THREAD

**Issue by vojirt** [votchallenge/vot-toolkit#92]
report_expected_overlap function now return only one output, however report_article (line 82) is calling this function and expects two outputs. This problem may be in other parts of code as well.

**Comment by lukacu** [comment]
Yes, I have been working on changing the reports a bit recently, but forgot to change all functionality. Actually we should rework the entire reporting infrastructure because it is quite messy at the moment (and getting more messy with every change).
