### ISSUE TITLE
failed to load: liboctave.so.2

### ISSUE THREAD

**Issue by fhdiaze** [votchallenge/vot-toolkit#94]
I am trying to run run_test.m script but I get this error:

error: create_sequence: /home/fhdiaze/Code/Vot/vot-toolkit/native/read_trajectory.mex: failed to load: liboctave.so.2: cannot open shared object file: No such file or directory

I am using GNU Octave, version 4.0.0. I deleted the native folder and run again but still get the same error. What can I do?

**Comment by lukacu** [comment]
The pre-compiled mex files were compiled for Octave 3.x and are not compatible with Octave 4.x. At the time of creating the build scripts this was a reasonable idea since Octave 3.x was much more prominent. We have to update our scripts but in the mean time you can build the binaries yourself (check the initialize_native.m for more details).

**Comment by fhdiaze** [comment]
Thank you for the response. I am trying to compile the files but I am getting the next error:

/home/fhdiaze/Code/Vot/vot-toolkit/sequence/region_mask.cpp: In function âvoid mexFunction(int, mxArray**, int, const mxArray**)â:
/home/fhdiaze/Code/Vot/vot-toolkit/sequence/region_mask.cpp:102:41: error: âregion_maskâ was not declared in this scope
     region_mask(p, result, width, height);

**Comment by lukacu** [comment]
One reason for this may be that you have an outdated version of the toolkit that is no longer compatible with some of the source files that are downloaded before compiling, the current version on Github should not have this problem.

**Comment by fhdiaze** [comment]
Hi,

I downloaded the code again. Now when I run test I get this error:

error: TraX support not available (client binary not found)

Who compiles the trax client? 

Thanks.

**Comment by lukacu** [comment]
Well the problem with manual compilation is that Matlab can only compile mex files and not executables, so compiling traxclient has to be done manually. The other option is to download the pre-compiled bundle manually and just extract the traxclient executable from it and place it in to the native folder, it will work with any version of Octave. I know that this is quite complicated, we will try to upgrade our build server in the following week for octave 4.0 and then there will be no more problems like this.

**Comment by lukacu** [comment]
I have updated builds for 32 and 64 bit Linux, please tell me if the updated version works for you by deleting the native folder and re-running the toolkit.

**Comment by fhdiaze** [comment]
Now, trax is working. Now I have a problem with my tracker. If I run my python tracker form a ipython console it works, but when I run a test it fails because it does not find the lib libcublas.so.7.5. Also, I add this line to the configuration.m file: set_global_variable('python', 'ipython');.

run_test detects trax support, but fails when execute the test using a sequence:

Testing TraX protocol support for tracker DeepTracker.
INFO: Executing "/home/fhdiaze/Code/Vot/vot-toolkit/native/traxclient -Q -t 30 -e "TRAX=1" -- ipython  -c "import sys; sys.path.append('/home/fhdiaze/Code/Vot/vot-toolkit/native/python');sys.path.append('/home/fhdiaze/Code/DeepTracking/tracking/util/data/'); import VotIntegrator"".
TraX support is present.

Is there some particularity of the toolkit to take into account? Is the toolkit using other ipython configuration?

**Comment by lukacu** [comment]
Ok, in this case I will close this issue and direct you to our [support forum](https://groups.google.com/forum/?hl=en#!forum/votchallenge-help), because this is now getting off-topic.
