### ISSUE TITLE
Error: Tracker exited with exit code 0

### ISSUE THREAD

**Issue by C-peng** [votchallenge/vot-toolkit#99]
What is the matter? It can generate a directory with input data for manual test, but can not run tracker once within the evaluation. Display "Error: Tracker exited with exit code 0".

**Comment by lukacu** [comment]
If you want to submit a bug report you will have to be more precise. What is the operating system and Matlab/Octave version that you are using? What is the command that you are trying to run? Also, are there any log outputs generated?

**Comment by C-peng** [comment]
Make sense

 

发件人: Luka Čehovin [mailto:notifications@github.com] 
发送时间: 2016年10月13日 15:16
收件人: votchallenge/vot-toolkit
抄送: Peng Cheng; Author
主题: Re: [votchallenge/vot-toolkit] Error: Tracker exited with exit code 0 (#99)

 

If you want to submit a bug report you will have to be more precise. What is the operating system and Matlab/Octave version that you are using? What is the command that you are trying to run? Also, are there any log outputs generated?

**Comment by lukacu** [comment]
No response for a few months, closing the issue. In the future please ask such questions on the support forum.
